(function(g){var window=this;'use strict';var EU=function(W){W.isActive()||W.start()},kZ=function(W){var l={languageCode:W.languageCode,
languageName:W.languageName,displayName:g.QD(W),kind:W.kind,name:W.name,id:W.id,is_servable:W.G,is_default:W.isDefault,is_translateable:W.isTranslateable,vss_id:W.vssId};W.xtags&&(l.xtags=W.xtags);W.captionId&&(l.captionId=W.captionId);W.translationLanguage&&(l.translationLanguage=W.translationLanguage);return l},a3G=function(W,l){var n=new g.iT;
n.languageCode=W.languageCode;n.languageName=W.languageName;n.name=W.name;n.displayName=W.displayName;n.kind=W.kind;n.isDefault=!1;n.G=W.G;n.isTranslateable=W.isTranslateable;n.vssId=W.vssId;n.url=W.url;n.translationLanguage=l;W.xtags&&(n.xtags=W.xtags);W.captionId&&(n.captionId=W.captionId);return n},bN=function(W,l){return l?W.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},ifw=function(W){return g.om(W)||W.A("web_enable_caption_language_preference_stickiness")},ZfG=async function(W,l){W=
W+"|"+l;
l=await g.ry();if(!l)throw g.iD("gct");return(await g.Ms(l)).get("captions",W)},wfT=function(W,l,n){ZfG(W,l).then(y=>{y&&n(y.trackData,new g.iT(y.metadata))})},MW=function(W){if(!f3G.test(W))throw Error("'"+W+"' is not a valid hex color");
W.length==4&&(W=W.replace(pfw,"#$1$1$2$2$3$3"));W=W.toLowerCase();W=parseInt(W.slice(1),16);return[W>>16,W>>8&255,W&255]},qSG=function(){var W={},l="suggest_correction"in g.z0?g.z0.suggest_correction:"Edit caption";
l=l||"";for(let n in W){let y=()=>String(W[n]);
l=l.replace(new RegExp("\\$\\{"+n+"\\}","gi"),y);l=l.replace(new RegExp("\\$"+n,"gi"),y)}return l},zb=function(){return g.bl("yt-player-caption-display-settings")},sfT=function(W,l){g.C0(l,n=>W.equals(n))||l.push(W)},hi=function(W,l){switch(l.kind){case "asr":sfT(l,W.S);
break;default:sfT(l,W.Z)}},D4b=async function(W,l,n){W.Z=g.AD(l,n)},SSv=function(W,l){var n=g.p9(W.segments,l);
n>=0||n<0&&(-n-1)%2===1||(n=-n-1,n>0&&l-W.segments[n-1]===1&&n<W.segments.length&&W.segments[n]-l===1?(g.Ue(W.segments,n),g.Ue(W.segments,n-1)):n>0&&l-W.segments[n-1]===1?W.segments[n-1]=l:n<W.segments.length&&W.segments[n]-l===1?W.segments[n]=l:(g.Z2(W.segments,n,0,l),g.Z2(W.segments,n+1,0,l)))},FGo=function(W){return W.G&&W.G.K?W.G.K+W.player.WO()<W.player.getCurrentTime():!1},onz=function(W,l){if(W.policy.tR&&W.player.w1()){var n=g.BE(l,W.policy,{});
n.set("pot",W.player.w1());n=n.fS()}else n=g.BE(l,W.policy,{}).fS();var y={format:"RAW",withCredentials:!0};if(W.policy.b$){y.method="POST";let w=l.J;w&&Object.keys(w).length>0?y.postBody=g.k9(w,g.Rb):y.postBody=(0,g.Qe)([120,0])}W.K&&(y.responseType="arraybuffer");var a=++W.vt,Z=(0,g.C)();W.Z=g.nI(n,y,3,100,-1,w=>{w.errorCode==="net.timeout"&&W.player.j("capnt",{rn:a++})}).then(w=>{if(W.policy.aE&&a%100===1){var f=(0,g.C)();
W.player.j("caprsp",{rn:a,ms:f-Z,kb:(w.xhr.responseText.length/1024).toFixed()})}a:{w=w.xhr;W.OL();if(W.S){var p=!(W.K?w.response:w.responseText)||w.status>=400;if(f=g.s0(w)){w=g.BE(W.S,W.policy,{});W.S.Wv(w,f);onz(W,W.S);break a}p?W.player.j("capfail",{status:w.status}):(g.F_("fcb_r",(0,g.C)(),W.player.getVideoData()?.xd||""),f=W.S.j$[0],p=f.sL,W.L!=null&&W.O!==p&&(W.K?W.L(w.response,(f.segmentStartTime+W.player.WO())*1E3):W.L(w.responseText,(f.segmentStartTime+W.player.WO())*1E3),W.O=p))}W.S=null;
W.Z=null}}).z$(w=>{W.S=null;
W.Z=null;W.player.j("capfail",{rn:a,status:w.xhr?.status})});
W.S=l;SSv(W.J,W.S.j$[0].sL)},c7z=function(W,l){return l!=null&&l in W.Z.G?W.Z.G[l]:null},EnT=function(W,l,n){var y=[];
for(let a in W.Z.G){if(!W.Z.G.hasOwnProperty(a))continue;let Z=W.Z.G[a];if(g.dN(Z,n||null)){let w=Z.info.captionTrack;w&&w.languageCode===l&&y.push(Z)}}return y.length?y[0]:null},knz=function(W,l){var n=[];
for(let a in W.Z.G){if(!W.Z.G.hasOwnProperty(a))continue;var y=W.Z.G[a];if(g.dN(y,l||null)){let Z=y.info.id,w=Z,f=`.${Z}`,p="",q="";if(y=y.info.captionTrack)Z=y.languageCode,w=y.displayName,f=y.vssId,p=y.kind,q=y.id;n.push(new g.iT({id:a,languageCode:Z,languageName:w,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f,kind:p,captionId:q}))}}return n},Qg=function(W){if(typeof DOMParser!="undefined")return g.by(new DOMParser,g.aC(W),"application/xml");
throw Error("Your browser does not support loading xml documents");},bfo=function(W,l,n,y){var a=l/360*16;
l>=W&&(W=640,y>n*1.3&&(W=480),a=n/W*16);return a},MRw=function(W){var l=1+.25*(W.fontSizeIncrement||0);
if(W.offset===0||W.offset===2)l*=.8;return l},z_w=function(W,l){var n="vertical-rl";
W.G.CZ===1&&(n="vertical-lr");g.px&&(n=n==="vertical-lr"?"tb-lr":"tb-rl");g.$Y(l,"-o-writing-mode",n);g.$Y(l,"-webkit-writing-mode",n);g.$Y(l,"writing-mode",n);g.$Y(l,"text-orientation","upright");g.br(l,"ytp-vertical-caption");W.S.params.Ib===3&&(g.$Y(l,"text-orientation",""),g.$Y(l,"transform","rotate(180deg)"))},h_o=function(W,l){var n={},y=l.background?l.background:W.G.Ll.background;
if(l.backgroundOpacity!=null||l.background){var a=l.backgroundOpacity!=null?l.backgroundOpacity:W.G.Ll.backgroundOpacity;y=MW(y);n.background="rgba("+y[0]+","+y[1]+","+y[2]+","+a+")";W.Ht&&(n["box-decoration-break"]="clone",n["border-radius"]=`${W.CR*.25}px`)}if(l.fontSizeIncrement!=null||l.offset!=null)n["font-size"]=`${W.Ma*MRw(l)}px`;W.experiments.X9("enable_player_captions_new_style_defaults")&&(n["line-height"]="1.375");y=1;a=l.color||W.G.Ll.color;if(l.color||l.textOpacity!=null)a=MW(a),y=l.textOpacity==
null?W.G.Ll.textOpacity:l.textOpacity,a="rgba("+a[0]+","+a[1]+","+a[2]+","+y+")",n.color=a,n.fill=a;var Z=l.charEdgeStyle;Z===0&&(Z=void 0);if(Z){a=`rgba(34, 34, 34, ${y})`;let p=`rgba(204, 204, 204, ${y})`;l.lU&&(p=a=l.lU);let q=W.Ma/16/2,D=Math.max(q,1);var w=Math.max(2*q,1),f=Math.max(3*q,1);let S=Math.max(5*q,1);y=[];switch(Z){case 4:for(;f<=S;f+=q)y.push(`${w}px ${w}px ${f}px ${a}`);break;case 1:w=window.devicePixelRatio>=2?.5:1;for(Z=D;Z<=f;Z+=w)y.push(`${Z}px ${Z}px ${a}`);break;case 2:y.push(`${D}px ${D}px ${p}`);
y.push(`-${D}px -${D}px ${a}`);break;case 3:for(f=0;f<5;f++)y.push(`0 0 ${w}px ${a}`)}n["text-shadow"]=y.join(", ")}a="";switch(l.fontFamily){case 1:a='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:a='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:a='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:a='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:a='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:a=g.zU()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:a='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}a&&(n["font-family"]=a);a=l.offset;a==null&&(a=W.G.Ll.offset);switch(a){case 0:n["vertical-align"]="sub";break;case 2:n["vertical-align"]="super"}l.fontFamily===7&&(n["font-variant"]="small-caps");l.bold&&(n["font-weight"]="bold");l.italic&&(n["font-style"]="italic");l.underline&&
(n["text-decoration"]="underline");l.v7&&(n.visibility="hidden");l.I2===1&&W.O&&(n["text-combine-upright"]="all",n["text-orientation"]="mixed",a=g.hO||g.nK,W.S.params.Ib===3?n.transform=a?"rotate(90deg)":"rotate(180deg)":a&&(n.transform="rotate(-90deg)"));if(l.textEmphasis===1||l.textEmphasis===2||l.textEmphasis===3||l.textEmphasis===4||l.textEmphasis===5)if(g.hO)n["font-weight"]="bold";else switch(n["text-emphasis-style"]="filled circle",n["text-emphasis-color"]="currentcolor",n["webkit-text-emphasis"]=
"filled circle",l.textEmphasis){case 4:case 3:n["text-emphasis-position"]="under left";n["webkit-text-emphasis-position"]="under left";break;case 5:case 2:n["text-emphasis-position"]="over right",n["webkit-text-emphasis-position"]="over right"}return n},QfK=function(W,l){if(W.qa&&l.length===0)return 0;
W=1;for(let n=0;n<l.length;n++){let y=l[n];typeof y.text==="string"&&(W+=y.text.split("\n").length-1,y.append||n===0||W++)}return W},vM=function(W){W=W.split("px");
return W.length>0?(W=Number(W[0]))?W:0:0},gnb=function(W,l,n){W.RX=W.RX||!!n;
var y={};Object.assign(y,W.G.Ll);Object.assign(y,n||l.G);Object.assign(y,W.X7.Ll);(n=!W.W)&&vna(W);var a=W.e$&&W.Pt&&g.ZR(y,W.Pt)?W.e$:e_G(W,y),Z=typeof l.text==="string",w=Z?l.text.split("\n"):[l.text];for(let p=0;p<w.length;p++){var f=p>0||!l.append;let q=w[p];f&&!n?(vna(W),a=e_G(W,y)):f&&n&&(n=!1);q&&(a.appendChild(Z?g.Gx(q):q),Z||q.tagName!=="RUBY"||q.childElementCount!==4||g.hO||!g.lv(q.children[2],"text-emphasis")||(f=W.O?"padding-right":"padding-top",g.lv(q.children[2],"text-emphasis-position")&&
(f=W.O?"padding-left":"padding-bottom"),g.zx?g.$Y(a,f,"1em"):g.$Y(a,f,"0.5em")))}W.Pt=y;W.e$=a;W.U.push(l)},vna=function(W){if(W.W){var l=W.W;
if(W.Ht){var n=W.G.textAlign;n===0?(l=l.firstElementChild)&&g.$Y(l,{"border-bottom-left-radius":"0"}):n===1&&(l=l.lastElementChild)&&g.$Y(l,{"border-bottom-right-radius":"0"})}}W.W=g.jy("SPAN");g.$Y(W.W,{display:"block"});g.br(W.W,"caption-visual-line");W.K.appendChild(W.W)},e_G=function(W,l){var n=g.jy("SPAN");
g.$Y(n,{display:"inline-block","white-space":"pre-wrap"});g.$Y(n,h_o(W,l));n.classList.add("ytp-caption-segment");W.W.appendChild(n);W.Ht&&W.K.children.length>1&&(W=W.G.textAlign,W===0?n.previousElementSibling||g.$Y(n,{"border-top-left-radius":"0"}):W===1&&g.$Y(n,{"border-top-right-radius":"0"}));n.previousElementSibling&&(g.$Y(n.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.$Y(n,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return n},
jfG=function(W,l,n){if(W===255&&l===255||!W&&!l)return{La:W,
dj:l,result:0};W=I3z[W];l=I3z[l];if(W&128){var y;if(y=!(l&128))y=l,y=n.Em()&&n.dj===y;if(y)return{La:W,dj:l,result:1}}else if(l&128&&1<=W&&W<=31)return{La:W,dj:l,result:2};return{La:W,dj:l,result:3}},KGw=function(W,l,n,y){l===255&&n===255||!l&&!n?(++W.S===45&&W.reset(),W.J.Z.clear(),W.K.Z.clear()):(W.S=0,GnG(W.J,l,n,y))},P9J=function(W,l){W.G.sort((n,y)=>{var a=n.time-y.time;
return a===0?n.order-y.order:a});
for(let n of W.G)W.time=n.time,n.type===0?KGw(W,n.Wr,n.gu,l):n.type===1&&W.Z&496&&GnG(W.K,n.Wr,n.gu,l);W.G.length=0},YSG=function(W,l){switch(W){case 0:return Hfo[(l&127)-32];
case 1:return R_a[l&15];case 2:return XfT[l&31];case 3:return x4K[l&31]}return 0},eb=function(W,l){if(W.style.type===3){var n=0,y=0,a=W.K.time+0,Z="",w="",f=a;
for(var p=1;p<=15;++p){var q=!1;for(var D=y?y:1;D<=32;++D){var S=W.S[p][D];if(S.G!==0){n===0&&(n=p,y=D);q=String.fromCharCode(S.G);var F=S.timestamp;F<a&&(a=F);S.timestamp=f;w&&(Z+=w,w="");Z+=q;q=!0}if((S.G===0||D===32)&&q){w="\n";break}else if(y&&!q)break}if(n&&!q)break}Z&&l.J(n,y,a,f,Z)}else for(y=n=0,Z=a=W.K.time+0,w=1;w<=15;++w)for(f="",p=1;p<=32;++p)if(D=W.S[w][p],S=D.G,S!==0&&(n===0&&(n=w,y=p),q=String.fromCharCode(S),F=D.timestamp,F<=a&&(a=F),f+=q,D.reset()),p===32||S===0)f&&l.J(n,y,a,Z,f),
a=Z,f="",y=n=0},gL=function(W){return W.S[W.row][W.Z]},Iv=function(W,l,n){l>=2&&W.Z>1&&(--W.Z,gL(W).G=0);
var y=gL(W);y.timestamp=W.K.time+0;y.G=YSG(l,n);W.Z<32&&W.Z++},LGK=function(W,l,n,y){for(let w=0;w<y;w++)for(let f=0;f<=32;f++){var a=W.S[l+w][f],Z=W.S[n+w][f];
a.G=Z.G;a.timestamp=Z.timestamp}},jb=function(W,l,n){for(let y=0;y<n;y++)for(let a=0;a<=32;a++)W.S[l+y][a].reset()},Gb=function(W){W.row=W.G>0?W.G:1;
W.Z=1;jb(W,0,15)},tRG=function(W){W.style.set(1);
W.G=W.J;W.G.G=0;W.G.style=W.style;W.S.mode=1<<W.G.J},K2=function(W,l,n){var y=W.Z,a=!1;
switch(W.style.get()){case 4:case 1:case 2:W.style.get()===4&&y.G>0||(eb(y,n),Gb(W.Z),Gb(W.J),y.row=15,y.G=l,a=!0)}W.style.set(3);W.G=y;W.G.style=W.style;W.S.mode=1<<y.J;a?y.Z=1:y.G!==l&&(y.G>l?(eb(y,n),jb(y,y.row-y.G,l)):y.row<l&&(l=y.G),y.G=l)},m4b=function(W){W.style.set(4);
W.G=W.text;W.G.style=W.style;W.S.mode=1<<W.G.J},GnG=function(W,l,n,y){W.Z.update();
l=jfG(l,n,W.Z);switch(l.result){case 0:return;case 1:case 2:return}var a=l.La;l=l.dj;if(32<=a||!a)W.G.mode&W.G.Z&&(n=a,n&128&&(n=127),l&128&&(l=127),W=W.J.G,n&96&&Iv(W,0,n),l&96&&Iv(W,0,l),n!==0&&l!==0&&W.style.type===3&&eb(W,y));else if(a&16)a:if(!W.Z.matches(a,l)&&(n=W.Z,n.La=a,n.dj=l,n.state=2,n=a&8?W.O:W.S,W.J=n,W.G.mode=1<<(W.K<<2)+(n.K<<1)+(n.style.type===4?1:0),(W.G.mode|1<<(W.K<<2)+(n.K<<1)+(n.style.type!==4?1:0))&W.G.Z))if(l&64){y=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(a&7)<<1|l>>5&1];
W=l&16?((l&14)>>1)*4:0;l=n.G;switch(n.style.get()){case 4:y=l.row;break;case 3:if(y!==l.row){if(y<l.G&&(y=l.G,y===l.row))break;var Z=1+l.row-l.G;let w=1+y-l.G;LGK(l,w,Z,l.G);n=Z;a=l.G;w<Z?(Z=w+a-Z,Z>0&&(n+=Z,a-=Z)):(Z=Z+a-w,Z>0&&(a-=Z));jb(l,n,a)}}l.row=y;l.Z=W+1}else switch(a&7){case 1:switch(l&112){case 32:Iv(n.G,0,32);break a;case 48:l===57?(y=n.G,gL(y).G=0,y.Z<32&&y.Z++):Iv(n.G,1,l&15)}break;case 2:l&32&&Iv(n.G,2,l&31);break;case 3:l&32&&Iv(n.G,3,l&31);break;case 4:case 5:if(32<=l&&l<=47)switch(l){case 32:tRG(n);
break;case 33:y=n.G;y.Z>1&&(--y.Z,gL(y).G=0);break;case 36:y=n.G;W=gL(y);for(l=0;l<=15;l++)for(n=0;n<=32;n++)if(y.S[l][n]===W){for(;n<=32;n++)y.S[l][n].reset();break}break;case 37:K2(n,2,y);break;case 38:K2(n,3,y);break;case 39:K2(n,4,y);break;case 40:Iv(n.G,0,32);break;case 41:y=n;y.style.set(2);y.G=y.Z;y.G.G=0;y.G.style=y.style;y.S.mode=1<<y.G.J;break;case 42:y=n;W=y.text;W.G=15;W.style.set(4);Gb(W);m4b(y);break;case 43:m4b(n);break;case 44:W=n;l=W.Z;switch(W.style.get()){case 1:case 2:case 3:eb(l,
y)}jb(l,0,15);break;case 45:b:{l=n;W=l.G;switch(l.style.get()){default:case 2:case 1:break b;case 4:if(W.row<15){++W.row;W.Z=1;break b}break;case 3:}W.G<2&&(W.G=2,W.row<W.G&&(W.row=W.G));l=W.row-W.G+1;eb(W,y);LGK(W,l,l+1,W.G-1);jb(W,W.row,1)}break;case 46:jb(n.J,0,15);break;case 47:W=n,eb(W.Z,y),W.J.updateTime(W.S.time+0),y=W.J,W.J=W.Z,W.Z=y,tRG(W)}break;case 7:switch(l){case 33:case 34:case 35:y=n.G,(y.Z+=l&3)>32&&(y.Z=32)}}},BIK=function(W,l,n,y,a,Z,w){var f=Z[0],p=w[f.getAttribute("p")];
if(p.wP===1){var q=Z[1],D=Z[2];Z=Z[3];f.getAttribute("t");q.getAttribute("t");D.getAttribute("t");Z.getAttribute("t");f.getAttribute("p");q.getAttribute("p");Z.getAttribute("p");w=w[D.getAttribute("p")];f=VRK(f.textContent,q.textContent,D.textContent,Z.textContent,w);return new PM(W,l,a,n,f,y,p)}switch(p.wP){case 9:case 10:p.textEmphasis=1;break;case 11:p.textEmphasis=2;break;case 12:p.textEmphasis=3;break;case 13:p.textEmphasis=4;break;case 14:p.textEmphasis=5}return new PM(W,l,a,n,f.textContent||
"",y,p)},VRK=function(W,l,n,y,a){var Z=g.zU(),w=Z?g.jy("DIV"):g.jy("RUBY"),f=g.jy("SPAN");
f.textContent=W;w.appendChild(f);W=Z?g.jy("DIV"):g.jy("RP");W.textContent=l;w.appendChild(W);l=Z?g.jy("DIV"):g.jy("RT");l.textContent=n;w.appendChild(l);n=a.wP;if(n===10||n===11||n===12||n===13||n===14)if(g.$Y(l,"text-emphasis-style","filled circle"),g.$Y(l,"text-emphasis-color","currentcolor"),g.$Y(l,"webkit-text-emphasis","filled circle"),a.wP===11||a.wP===13)g.$Y(l,"webkit-text-emphasis-position","under left"),g.$Y(l,"text-emphasis-position","under left");n=!0;if(a.wP===4||a.wP===7||a.wP===12||
a.wP===14)g.$Y(w,"ruby-position","over"),g.$Y(w,"-webkit-ruby-position","before");else if(a.wP===5||a.wP===6||a.wP===11||a.wP===13)g.$Y(w,"ruby-position","under"),g.$Y(w,"-webkit-ruby-position","after"),n=!1;a=Z?g.jy("DIV"):g.jy("RP");a.textContent=y;w.appendChild(a);Z&&(y=n,g.$Y(w,{display:"inline-block",position:"relative"}),Z=w.firstElementChild.nextElementSibling,g.$Y(Z,"display","none"),Z=Z.nextElementSibling,g.$Y(Z,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.$Y(w.lastElementChild,"display","none"),y?(g.$Y(w,"padding-top","0.6em"),g.$Y(Z,"top","0")):(g.$Y(w,"padding-bottom","0.6em"),g.$Y(Z,"bottom","0")));return w},r7v=function(W){var l="_"+HM++;
return new Rv(0,0x8000000000000,0,l,W)},X2=function(W,l){W=W.getAttribute(l);
if(W!=null)return Number(W)},xZ=function(W,l){W=W.getAttribute(l);
if(W!=null)return W==="1"},YZ=function(W,l){W=X2(W,l);
return W!==void 0?W:null},ti=function(W,l){W=W.getAttribute(l);
if(W!=null)return L2.test(W),W},TIv=function(W,l){var n={},y=l.getAttribute("ws");
Object.assign(n,y?W.U[y]:W.J);W=YZ(l,"mh");W!=null&&(n.Ea=W);W=YZ(l,"ju");W!=null&&(n.textAlign=W);W=YZ(l,"pd");W!=null&&(n.Ib=W);W=YZ(l,"sd");W!=null&&(n.CZ=W);W=ti(l,"wfc");W!=null&&(n.windowColor=W);l=X2(l,"wfo");l!==void 0&&(n.windowOpacity=l/255);return n},NIK=function(W,l){var n={},y=l.getAttribute("wp");
y&&Object.assign(n,W.L[y]);W=YZ(l,"ap");W!=null&&(n.mu=W);W=X2(l,"cc");W!=null&&(n.Ih=W);W=X2(l,"ah");W!=null&&(n.jU=W);W=X2(l,"rc");W!=null&&(n.rW=W);l=X2(l,"av");l!=null&&(n.vE=l);return n},C9o=function(W,l,n,y){var a={};
Object.assign(a,NIK(W,l));Object.assign(a,TIv(W,l));y?g.ZR(a,W.J)?(y=W.K,a=W.J):y="_"+HM++:y=l.getAttribute("id")||"_"+HM++;W=X2(l,"t")+n;l=X2(l,"d")||0x8000000000000;if(a.Ib===2||a.Ib===3)n=a.rW,a.rW=a.Ih,a.Ih=n;return new Rv(W,l,0,y,a)},mR=function(W){W=g.Lv(Math.round(W),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-W.length)+W},d4v=function(W,l,n,y,a){y===0&&(y=0x8000000000000);
var Z={};l.wpWinPosId&&Object.assign(Z,W.J.get(l.wpWinPosId));l.wsWinStyleId&&Object.assign(Z,W.K.get(l.wsWinStyleId));W=l.rcRowCount;W!==void 0&&(Z.rW=W);l=l.ccColCount;l!==void 0&&(Z.Ih=l);if(Z.Ib===2||Z.Ib===3)l=Z.rW,Z.rW=Z.Ih,Z.Ih=l;return new Rv(n,y,0,a,Z)},Vg=function(W){var l=W.byteOffset;
W.byteOffset+=1;return W.G.getUint8(l)},BM=function(W){var l=W.byteOffset;
W.byteOffset+=4;return W.G.getUint32(l)},Ofw=function(W){if(typeof W==="string")return!1;
W=new A7o(W,0);return J7q(W)},J7q=function(W){if(!(W.byteOffset<W.G.byteLength)||BM(W)!==1380139777)return!1;
W.version=Vg(W);if(W.version>1)return!1;Vg(W);Vg(W);Vg(W);return!0},$4q=function(W,l){if(!l)return"";
W.O&&W.S.params.CZ!==1&&(l*=-1);return`translate${W.O?"X":"Y"}(${l}px)`},u5w=function(W){W.gS=Array.from(W.element.getElementsByClassName("caption-visual-line"));
for(var l=W.S.params.rW,n=0,y=0,a=W.gS.length-1;n<l&&a>-1;){var Z=W.gS[a];y+=W.O?Z.offsetWidth:Z.offsetHeight;n++;a--}W.vt=y;l=Math;n=l.max;isNaN(W.b$)&&((y=W.G.Ih)?(a=g.jy("SPAN"),g.XW(a,"\u2013".repeat(y)),g.$Y(a,h_o(W,W.G.Ll)),W.K.appendChild(a),W.b$=a.offsetWidth,W.K.removeChild(a)):W.b$=0);y=W.K;W.rS=n.call(l,W.b$,W.W$,(W.O?y.offsetHeight:y.offsetWidth)+1)},U4o=function(W,l){u5w(W);
var n=W.gS.reduce((y,a)=>(W.O?a.offsetWidth:a.offsetHeight)+y,0);
n=W.vt-n;if(n!==W.Y5){let y=n>0&&W.Y5===0,a=n<W.Y5;l||isNaN(n)||y||!a||(g.br(W.element,"ytp-rollup-mode"),W.yK(W.element,"transitionend",W.xV));g.$Y(W.K,"transform",$4q(W,n));W.Y5=n}u5w(W)},lnw=function(W,l,n,y){var {formatId:a,
sL:Z,startTimeMs:w,durationMs:f}=W.W(l),p={formatId:a,startTimeMs:w,durationMs:f,Be:Z,v$:Z},q=WsT(W.FG,p.startTimeMs),D=q>=0?W.FG[q]:null,S=D?D.startTimeMs+D.durationMs:0,F=p.startTimeMs+p.durationMs;!D||p.startTimeMs-S>W.J?W.FG.splice(q+1,0,p):(D.durationMs=Math.max(S,F)-D.startTimeMs,D.v$=Math.max(D.v$,p.v$));y(W.FG);y=g.a5(l);W=W.K;y=y.buffer.slice(y.byteOffset,y.byteLength+y.byteOffset);l=l.info.J;W.GH?W.L==null?g.lA(W.logger,350058965,"Null loaded track meta data at captions data received"):
n.p$(y,W.L,l*1E3):g.lA(W.logger,350058965,"Null Representation at captions data received")},anq=function(W,l){W.Z=(n,y)=>{if(W.B.D().experiments.X9("html5_sabr_live_support_subfragmented_captions"))(W.G?W.G=W.G.K(n):(W.G=n,nQG(W.G)),W.G)?n.info.dY&&(yub(W.G),lnw(W,W.G,l,y),W.G=null):g.lA(W.logger,350058965,"Empty slice");
else if(n.info.dY){var a=n;if(W.mL.length>0){for(a=W.mL.shift();W.mL.length>0;)a=a?.K(W.mL.shift());a=a?.K(n)}a?(nQG(a),yub(a),lnw(W,a,l,y)):g.lA(W.logger,350058965,"Empty slice")}else W.mL.push(n)};
W.B.addEventListener("sabrCaptionsDataLoaded",W.Z)},WsT=function(W,l){W=g.p9(W,{startTimeMs:l},(n,y)=>n.startTimeMs-y.startTimeMs);
return W>=0?W:-W-2},nQG=function(W){try{var l=g.fh(W)*1E3}catch(n){l=W.info.segmentStartTime*1E3}l<0&&(l=W.info.segmentStartTime*1E3);
W.info.segmentStartTime=l/1E3;W.info.J=l/1E3},yub=function(W){try{var l=g.S6(W)*1E3}catch(n){l=W.info.S*1E3}l<0&&(l=W.info.S*1E3);
W.info.S=l/1E3;W.info.W=l/1E3},ijw=function(W,l){if(!g.Ta(W)||W.G!=null&&g.CR(l,W.G)&&W.G.G.rawcc!=null)return!1;
l=!!W.G&&W.G.isManifestless&&Object.values(W.G.G).some(n=>g.dN(n,"386"));
W=!!W.G&&!W.G.isManifestless&&g.P$(W.G);return l||W},Zjv=function(W,l,n){var y=[];
for(let a in W.Z.G){if(!W.Z.G.hasOwnProperty(a))continue;let Z=W.Z.G[a];if(g.dN(Z,n||null)){let w=Z.info.captionTrack;w&&w.languageCode===l&&y.push(Z)}}return y.length?y[0]:null},wDq=function(W,l){var n=[];
for(let a in W.Z.G){if(!W.Z.G.hasOwnProperty(a))continue;var y=W.Z.G[a];if(g.dN(y,l||null)){let Z=y.info.id,w=Z,f=`.${Z}`,p="",q="";if(y=y.info.captionTrack)Z=y.languageCode,w=y.displayName,f=y.vssId,p=y.kind,q=y.id;n.push(new g.iT({id:a,languageCode:Z,languageName:w,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f,kind:p,captionId:q}))}}return n},pDK=function(W){var l=fnK.length;
if(W.byteLength<l)return!1;W=new Uint8Array(W,0,l);for(let n=0;n<l;n++)if(fnK[n]!==W[n])return!1;return!0},rL=function(W){W=W.split(":");
var l=0;for(let n of W)l=l*60+Number(n);return l*1E3},qnb=function(W,l,n,y){y=Object.assign({Ea:0},y);
return new Rv(W,l,n,"_"+HM++,y)},sqJ=function(W,l,n,y,a,Z,w,f,p){switch(w.tagName){case "b":f.bold=!0;
break;case "i":f.italic=!0;break;case "u":f.underline=!0}for(let D=0;D<w.childNodes.length;D++){var q=w.childNodes[D];if(q.nodeType===3)q=new PM(l,n,y,a.id,q.nodeValue,Z||D>0,g.yH(f)?void 0:f),p.push(q),a.G.push(q);else{let S={};Object.assign(S,f);sqJ(W,l,n,y,a,!0,q,S,p)}}},SnK=function(W,l,n){if(typeof l==="string"||Ofw(l))return[{trackData:l,
Qu:n}];if(typeof l==="string"&&l.substring(0,6)==="WEBVTT"||typeof l!=="string"&&pDK(l))return[{trackData:l,Qu:n}];var y=new DataView(l);if(y.byteLength<=8||y.getUint32(4)!==1718909296)return[];var a=g.Ho(y);if(W.O4&&a){var Z=g.Fp(a),w=g.oR(a);a=a.segmentNumber;Z&&a&&W.O4.K5(a,Z,w)}W=g.Gp(y,1835295092);if(!W||!W.length||!W[0].size)return[];Z=[];for(w=0;w<W.length;w++)a=W[w],a=new Uint8Array(l,a.dataOffset,a.size-(a.dataOffset-a.offset)),a=g.Uv(a),Z.push({trackData:a,Qu:n+w*1E3});DxT(y,Z,n);return Z=
Z.filter(f=>!!f.trackData)},oQT=function(W,l,n){W.G||(W.G=new Fsv);
W=W.G.S(l,n);Math.random()<.01&&g.Ce(Error("Deprecated subtitles format in web player: WebVTT"));return W},DxT=function(W,l,n){var y=g.ME(W,0,1836476516),a=9E4;
y&&(a=g.QL(y)||9E4);y=0;var Z=g.Gp(W,1836019558);for(let f=0;f<Z.length;f++){var w=Z[f];f<l.length&&(w=g.ME(W,w.dataOffset,1953653094))&&(w=g.ME(W,w.dataOffset,1952867444))&&(w=g.IR(w)/a*1E3,f===0&&(y=w),l[f].Qu=w-y+n||n*f*1E3)}},cuo=function(W){var l={};
if(W=g.vN(W))l.lang=W,g.RUb.test(W)&&(l.Ib=1);return l},Tb=function(W){return W.S==="HLS"&&W.E4?!0:W.RX&&W.E4&&W.S!=="LIVE"&&W.S!=="SABR_LIVE"},EQa=function(W){return!W.J&&W.RX&&W.qa&&(W.S==="LIVE"||W.S==="SABR_LIVE")},NW=function(W,l,n=!1){var y=W.X.A("enable_player_captions_new_style_defaults")?kWK:bjz,a=y.Ll;
W.K={};Object.assign(W.K,y);W.K.Ll={};Object.assign(W.K.Ll,a);W.O={Ll:{}};var Z=l.backgroundOverride?W.O:W.K,w=l.background||a.background;L2.test(w);Z.Ll.background=w;Z=l.colorOverride?W.O:W.K;w=l.color||a.color;L2.test(w);Z.Ll.color=w;Z=l.windowColorOverride?W.O:W.K;w=l.windowColor||y.windowColor;L2.test(w);Z.windowColor=w;Z=l.backgroundOpacityOverride?W.O:W.K;w=l.backgroundOpacity;w==null&&(w=a.backgroundOpacity);Z.Ll.backgroundOpacity=w;Z=l.fontSizeIncrementOverride?W.O:W.K;w=l.fontSizeIncrement;
w==null&&(w=a.fontSizeIncrement);Z.Ll.fontSizeIncrement=w;w=l.fontStyleOverride?W.O:W.K;Z=l.fontStyle;Z==null&&(Z=a.bold&&a.italic?3:a.bold?1:a.italic?2:0);w=w.Ll;switch(Z){case 1:w.bold=!0;delete w.italic;break;case 2:delete w.bold;w.italic=!0;break;case 3:w.bold=!0;w.italic=!0;break;default:delete w.bold,delete w.italic}Z=l.textOpacityOverride?W.O:W.K;w=l.textOpacity;w==null&&(w=a.textOpacity);Z.Ll.textOpacity=w;Z=l.windowOpacityOverride?W.O:W.K;w=l.windowOpacity;w==null&&(w=y.windowOpacity);Z.windowOpacity=
w;y=l.charEdgeStyleOverride?W.O:W.K;Z=l.charEdgeStyle;Z==null&&(Z=a.charEdgeStyle);y.Ll.charEdgeStyle=Z;y=l.fontFamilyOverride?W.O:W.K;Z=l.fontFamily;Z==null&&(Z=a.fontFamily);y.Ll.fontFamily=Z;W.loaded&&W.Db();n&&g.kh("yt-player-caption-display-settings",l,2592E3)},C2=function(W,l,n){l&&!W.V?(l=r7v({Ib:0,
lang:"en-GB"}),W.V=[l,new PM(l.start,l.end-l.start,0,l.id,n??"Captions look like this")],W.player.us(W.V)):!l&&W.V&&(MxT(W,W.V),W.V=null)},hFK=function(W){if(W.X.A("enable_player_captions_persistence_state_machine")){var l=g.bl("yt-player-caption-persistence");
if(l==null){let n=g.ec().KR(65);if(n===!0)l=!1;else{let y=g.om(W.X)?dL(W):zFb(W);y!=null?l=!!y:n===!1&&(l=!0)}l!==void 0&&Ai(W,l)}return l}},dL=function(W){if(!W.B.isInline())return g.bl("yt-player-sticky-caption")},zFb=function(W){if(!W.storage)return null;
try{var l=W.storage.get("module-enabled")}catch(n){W.storage.remove("module-enabled")}return l},Ji=function(W){if(W.X.A("enable_player_captions_persistence_state_machine"))return hFK(W);
var l=void 0,n=g.ec().KR(65);if(g.om(W.X)&&n!=null){if(dL(W)!=null)return!1;l=!n}return l},Qqa=function(W){if(W.X.sT===1||W.videoData.pz===1||g.HV(W.videoData,"yt:cc")==="alwayson")return!0;
if(W.videoData.captionTracks.length)var l=W.getAudioTrack().Z;if(W.X.A("enable_player_captions_persistence_state_machine")){var n=hFK(W);if(n!==void 0)return!!n}else if(W.X.sT===2&&(g.om(W.X)?n=dL(W):n=zFb(W),n!=null))return!!n;n=bN(W.player.getAudioTrack(),g.om(W.X));var y=g.HV(W.videoData,"yt:cc");if(Ji(W)===void 0){if(n==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return y?y==="on":!0;if(n==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return y==="on"}else return y==="on";return l==="ON"||g.HV(W.videoData,
"yt:cc")==="on"},OU=function(W,l=!1){if(W.G&&!l||!W.videoData.captionTracks.length)return!1;
W=W.getAudioTrack();return!!W.G||W.Z==="FORCED_ON"},vQw=function(W){return W.X.A("html5_honor_caption_availabilities_in_audio_track")&&W.S!=="LIVE"&&W.S!=="SABR_LIVE"},eFJ=function(W,l){if(W.G){var n=W.B.ZE().Ed().textTracks,y=null;
W.S==="HLS"?y=W.G.getId():y=W.G.toString();for(let Z=0;Z<n.length;Z++){var a=n[Z];a.id===y&&(l?a.mode!=="showing"&&(a.mode="showing",a=W.G,W.wx(a,!!a,$Z(W)?"g":W.L?"m":"s")):a.mode==="showing"&&(a.mode="disabled"))}}},$Z=function(W){var l=uN(W);
return!!l&&W.G===l},gQG=function(W,l){if(W.S==="HLS")return!1;
g.VS(W.videoData)&&(l=!0);l||(l=W.S==="TTS"?!1:W.S==="INNERTUBE"?!1:!0);return l||W.X.A("web_watch_disable_account_level_captions_settings")&&g.om(W.X)?!0:!!g.ec().KR(66)},uN=function(W){return W.U&&W.U.G},UU=function(W,l){if(!W.Z)return null;
if(W.U&&W.U.J)return W.U.J;l=gQG(W,l);l=W.Z.G.G(l);var n=null;if(ifw(W.X)){var y=W.B.isInline()?void 0:g.bl("yt-player-caption-sticky-language");var a=[y,W.videoData.captionsLanguagePreference,W.X.captionsLanguagePreference,g.HV(W.videoData,"yt:cc_default_lang")];let f=!1;for(let p=0;p<a.length;p++){let q=a[p];if(q){f=!0;for(var Z=0;Z<l.length;Z++)if(g.vN(l[Z])===q)return l[Z];for(Z=0;Z<l.length;Z++)if(g.vN(l[Z]).split("-")[0]===q.split("-")[0])return l[Z]}}if(f&&W.Z&&(a=W.Z.U,a.length))for(var w of a)if(w.languageCode===
y){n=w;break}}else for(w=[W.videoData.captionsLanguagePreference,W.X.captionsLanguagePreference,g.HV(W.videoData,"yt:cc_default_lang")],y=0;y<w.length;y++)for(a=0;a<l.length;a++)if(g.vN(l[a])===w[y])return l[a];w=null;W.U&&W.U.S&&(w=W.U.S);w||(w=l.find(f=>f.isDefault)||null);
w||(w=l[0]||uN(W));w&&n&&g.vN(w).split("-")[0]!==n.languageCode.split("-")[0]&&(w=a3G(w,n));return w},yO=function(W,l,n){W.loaded&&W.unload();
n!=null&&(W.L=n,W.L&&(W.X.A("enable_player_captions_persistence_state_machine")?Ai(W,!!l):g.om(W.X)?Ww(W,!!l):lh(W,!!l)));l!==null||OU(W,!0)||W.wx(l,!!l,W.L?"m":"s");W.G=l;OU(W)&&(W.G=uN(W));nP(W,W.G??void 0);W.load()},Ai=function(W,l){W.X.A("enable_player_captions_persistence_state_machine")&&g.kh("yt-player-caption-persistence",l,3122064E3)},Ww=function(W,l){W.B.isInline()||g.kh("yt-player-sticky-caption",l,2592E3)},lh=function(W,l){if(W.storage)try{W.storage.set("module-enabled",l)}catch(n){}},
nP=function(W,l){W.X.A("html5_modify_caption_vss_logging")&&(W.videoData.ha=l)},jqb=function(W,l){var n=W.rS[l.id];
n&&n.S!==l&&(n.dispose(),delete W.rS[l.id],n=null);n||(n=Inw(W,l))&&(W.rS[l.id]=n)},GWG=function(W,l){var n=l.windowId;
W.Pt[n]||(W.Pt[n]=[]);W.Pt[n].push(l)},Inw=function(W,l){var n=KsG(W);
if(!n)return null;var y=W.G?g.vN(W.G):null;y&&g.RUb.test(y)&&(l.params.Ib=1);var a=W.xV.getPlayerSize();y=a.height*W.vt.height;a=a.width*W.vt.width;W.X.playerStyle!=="google-live"||W.K.isDefault||Object.assign(l.params,W.K);switch(l.params.Ea!=null?l.params.Ea:l.G.length>1?1:0){case 1:return new PLz(l,W.K,W.O,n.width,n.height,a,y,W.X.experiments,W.CR.bind(W),W.B);case 2:return new Hjb(l,W.K,W.O,n.width,n.height,a,y,W.X.experiments,W.CR.bind(W),W.B);default:return new aP(l,W.K,W.O,n.width,n.height,
a,y,W.X.experiments,W.CR.bind(W),W.B)}},KsG=function(W){var l=W.xV.getVideoContentRect(!0).height,n=W.xV.getVideoContentRect(!0).width;
if(!l||!n)return null;l*=W.vt.height;n*=W.vt.width;return{width:n,height:l}},MxT=function(W,l){W.player.yU(l);
for(let n of l)g.ly(W.gS,n);EU(W.b$)},RFa=function(W,l){if(!W.Z)return{};
if(l){g.yH(l)||W.GR(l.vss_id,"m");if(W.J&&W.S!=="HLS"||!g.vb(l))return;if(g.yH(l)){yO(W,null,!0);return}let y;var n=W.Z.G.G(!0);for(let a=0;a<n.length;a++){let Z=n[a];Z.languageCode!==l.languageCode||y&&(Z.languageName!==l.languageName||(Z.captionId||"")!==(l.captionId||"")||g.QD(Z)!==l.displayName)||(y=l.translationLanguage?a3G(Z,l.translationLanguage):Z)}W.Ji(l.position);!y||y===W.G&&W.loaded||(l=g.lp(),n=g.vN(y),l.length&&n===l[l.length-1]||(l.push(n),g.kh("yt-player-caption-language-preferences",
l)),ifw(W.X)&&!W.B.isInline()&&g.kh("yt-player-caption-sticky-language",n,2592E3),yO(W,y,!0))}else return W.loaded&&W.G&&!$Z(W)?kZ(W.G):{};return""};
g.gq.prototype.K5=g.aw(121,function(W,l,n){this.Z.set(W,{UK:l,E_:n})});
g.II.prototype.K5=g.aw(120,function(W,l,n){this.u$.K5(W,l,n)});
g.Q5.prototype.L=g.aw(119,function(){this.mediaElement.L()});
g.bQ.prototype.L=g.aw(118,function(){var W=g.Eb(document,"track",void 0,this.G);for(let l=0;l<W.length;l++)g.Hu(W[l])});
g.Q5.prototype.e$=g.aw(117,function(){return this.mediaElement.e$()});
g.bQ.prototype.e$=g.aw(116,function(){return!(!this.G.textTracks||!this.G.textTracks.addEventListener)});
g.Q5.prototype.RX=g.aw(115,function(){return this.mediaElement.RX()});
g.bQ.prototype.RX=g.aw(114,function(){return!!this.G.textTracks});
g.Q5.prototype.vt=g.aw(113,function(W){this.mediaElement.vt(W)});
g.bQ.prototype.vt=g.aw(112,function(W){for(let l=0;l<W.length;l++)this.G.appendChild(W[l])});
g.Wi.prototype.GR=g.aw(48,function(W,l){this.app.aX().GR(W,l)});
g.CO.prototype.GR=g.aw(47,function(W,l){this.N.GR(W,l)});
g.Fk.prototype.GR=g.aw(46,function(W,l){W=[W,l];g.um(this,g.W5(this.provider),"cfi",W)});
g.ko.prototype.GR=g.aw(45,function(W,l){this.qoe&&this.qoe.GR(W,l)});
g.NX.prototype.GR=g.aw(44,function(W,l){this.RY.GR(W,l)});
g.QJ.prototype.GR=g.aw(43,function(){});
g.Wi.prototype.wx=g.aw(42,function(W,l,n){this.app.aX().wx(W,l,n)});
g.CO.prototype.wx=g.aw(41,function(W,l,n){this.N.wx(W,l,n)});
g.Fk.prototype.wx=g.aw(40,function(W,l,n){if(this.Ht!==W||this.nb!==l)l=l==="rawcc"?"":l,n=[W,l,this.Ht,n],g.um(this,g.W5(this.provider),"cfs",n),this.Ht=W,this.nb=l});
g.ko.prototype.wx=g.aw(39,function(W,l,n){this.qoe&&this.qoe.wx(W,l,n)});
g.NX.prototype.wx=g.aw(38,function(W,l,n){this.RY.wx(W,l,n)});
g.QJ.prototype.wx=g.aw(37,function(){});
g.pR.prototype.iE=g.aw(11,function(){return this.O4});
g.KS.prototype.iE=g.aw(10,function(){return this.aX().HE()});
g.Wi.prototype.HE=g.aw(9,function(){return this.app.iE()});
g.CO.prototype.HE=g.aw(8,function(){return this.N.HE()});
g.NX.prototype.HE=g.aw(7,function(){return this.loader?.iE()||null});
g.QJ.prototype.HE=g.aw(6,function(){return null});
g.mg.prototype.Ad=g.aw(4,function(W){return(W=this.S(W))?W.G:0});
g.Bg.prototype.Ad=g.aw(3,function(){return 0});
g.iT.prototype.Z=g.aw(2,function(){return this.vssId});
var pfw=/#(.)(.)(.)/,f3G=/^#(?:[0-9a-f]{3}){1,2}$/i,XDq=class{constructor(){this.S=[];this.Z=[]}G(W){return W?this.Z.concat(this.S):this.Z}},ih=class extends g.$b{constructor(W){super();this.LR=W;this.G=new XDq;this.rS=new XDq;this.K=null;this.U=[];this.vt=[]}W(){}J(){}S(){}O(){return""}u$(){return!1}sA(W,l){if(this.LR.D().A("html5_dispatch_tracklist_loaded_event")){this.K&&(this.K.reject(),this.K=null);var n=[];this.LR.Zb("trackListLoaded",this.G,n,l);this.LR.D().A("enable_po_decoration_of_forced_tracks")&&
this.LR.Zb("trackListLoaded",this.rS,n,l);n.length?(l=new g.zQ,l.promise.then(W.sA,()=>{}),this.K=l,Promise.all(n).then(l.resolve,l.reject).finally(()=>{this.K=null})):W.sA()}else W.sA()}S$(){this.K&&(this.K.reject(),this.K=null);
this.S();super.S$()}},xxK={en:"English"},Yna=class extends ih{constructor(W){super(W);this.Z=new Set}J(W){var l=this.LR.ZE();if(l&&l.Ed()){l=l.Ed().textTracks;for(let n of l)n.kind==="subtitles"&&!this.Z.has(n.language)&&n.language&&(hi(this.G,new g.iT({languageCode:n.language,languageName:n.language,kind:n.kind,id:n.id,displayName:xxK[n.label]||n.label,vss_id:`.${n.language}`})),this.Z.add(n.language))}this.G.G().length>0&&W.sA()}},Lsv=class extends ih{constructor(W,l,n){super(W);this.videoData=
l;this.audioTrack=n;this.Z=null;this.L=!1;this.U=l.l2;this.vt=l.fI;this.L=g.VS(l)}W(W,l,n){this.OL();l=this.O(W,l);var y=this.LR.D().A("html5_report_captions_ctmp_qoe"),a=(0,g.C)();this.S();D4b(this,l,{format:"RAW",onSuccess:Z=>{this.Z=null;if(y){var w=(Z.responseText.length/1024).toFixed();let f=(0,g.C)();this.videoData.j("capresp",{ms:f-a,kb:w})}w=Z.getResponseHeader&&Z.getResponseHeader("Content-Length")?Number(Z.getResponseHeader("Content-Length")):0;n.p$(Z.responseText,W,void 0,void 0,w)},
onError:y?Z=>{this.videoData.j("capfail",{status:Z?.status??0})}:void 0,
withCredentials:!0})}J(W){if(this.audioTrack){for(let l of this.audioTrack.captionTracks)hi(this.G,l);this.audioTrack.G&&hi(this.rS,this.audioTrack.G)}this.sA(W,this.videoData.videoId)}O(W,l){var n=W.fS(),y={fmt:l};if(l==="srv3"||l==="3"||l==="json3")g.zU()?Object.assign(y,{xorb:2,xobt:1,xovt:1}):Object.assign(y,{xorb:2,xobt:3,xovt:3});W.translationLanguage&&(y.tlang=g.vN(W));this.L&&(y.xosf="1");Object.assign(y,this.LR.D().G);return g.eA(n,y)}S(){this.Z&&this.Z.abort()}},txK=class{constructor(){this.segments=
[]}contains(W){W=g.p9(this.segments,W);return W>=0||W<0&&(-W-1)%2===1}length(){return this.segments.length/2}},mxK=class extends g.$b{constructor(W,l,n,y,a,Z){super();this.policy=W;this.player=l;this.pR=n;this.L=y;this.K=a;this.GH=Z;this.J=new txK;this.O=-1;this.Z=this.S=this.G=null;this.vt=0;this.W=new g.Dx(this.U,1E3,this);this.events=new g.r9(this);g.Y(this,this.W);g.Y(this,this.events);this.events.yK(l,"SEEK_COMPLETE",this.V);this.V();this.U()}S$(){super.S$();this.Z&&this.Z.cancel()}V(){this.seekTo(this.player.getCurrentTime())}seekTo(W){W-=
this.player.WO();var l=this.G;this.G=g.L0(this.pR.W(W).j$);l!==this.G&&this.GH&&this.GH()}reset(){this.J=new txK;this.O=-1;this.Z&&(this.Z.cancel(),this.Z=null)}U(){this.OL();var W;if(W=this.G!=null)W=this.G,W=W.pR.J(W);if(W&&!this.Z&&!(this.G&&this.G.segmentStartTime-this.player.getCurrentTime()>30)){W=this.G;W=W.pR.RX(W);let a=W.j$[0];if(this.player.getVideoData()?.enableServerStitchedDai){var l=this.player.HE();if(l){var n=a.pR.info.id;let Z=a.sL;var y=W.j$[0].J;if(this.policy.b$){if(l=g.G1T(l,
y,Z,n,3))W.J=l}else if(n=l.Jd(y,Z,n,3))if(y=2,l.g1.has(Z)?y=0:g.CB(l,Z)&&(y=1),l=y,l===0)n&&(W.G=new g.Oe(n));else if(l===2){this.W.start();FGo(this)&&this.seekTo(this.player.getCurrentTime());return}}}a.pR.index.ik(a.sL)?(this.J.contains(W.j$[0].sL)||onz(this,W),this.G=g.L0(W.j$)):FGo(this)&&this.seekTo(this.player.getCurrentTime())}this.W.start()}},VxG=class extends ih{constructor(W,l){super(l);this.Z=W;this.B=l;this.L=null;this.V=!1;this.logger=new g.WC("caps");this.GH=g.CR(this.B,this.Z)}W(W,
l,n){this.S();l=c7z(this,W.getId());l||(l=W.languageCode,l=this.Z.isManifestless?EnT(this,l,"386"):EnT(this,l));if(l){var y=(l.index.Ad(l.index.ew())-l.index.getStartTime(l.index.ew()))*1E3,a=new g.uhv(this.B.D());this.L=new mxK(a,this.B,l,(Z,w)=>{n.p$(Z,W,w,y)},this.GH||g.cE(l.info),()=>{this.L&&this.L.reset();
this.V=!0})}}u$(){var W=this.V;
this.V=!1;return W}J(W){var l=this.B.D().A("html5_fallback_if_rawcc_missing");var n=this.Z.G.rawcc!=null;if(!this.GH||!n&&l)l=this.Z.isManifestless?knz(this,"386"):knz(this);else{if(!n){g.lA(this.logger,386248249,"rawcc used but unavailable");return}l=[new g.iT({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.iT({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let y of l)hi(this.G,
y);W.sA()}S(){this.L&&(this.L.dispose(),this.L=null)}O(){return""}},BuK=class extends ih{constructor(W,l,n,y,a,Z){super(W);this.videoId=n;this.V=a;this.eventId=Z;this.GH={};this.Z=null;W=y||g.Qn(l).hl||"";W=W.split("_").join("-");this.L=g.eA(l,{hl:W})}W(W,l,n){this.OL();l=this.O(W,l);this.S();this.Z=g.AD(l,{format:"RAW",onSuccess:y=>{this.Z=null;var a=y.getResponseHeader&&y.getResponseHeader("Content-Length")?Number(y.getResponseHeader("Content-Length")):0;n.p$(y.responseText,W,void 0,void 0,a)},
withCredentials:!0})}J(W){var l=this.L,n={type:"list",tlangs:1,v:this.videoId,vssids:1};this.V&&(n.asrs=1);l=g.eA(l,n);this.S();this.Z=g.AD(l,{format:"RAW",onSuccess:y=>{this.Z=null;if((y=y.responseXML)&&y.firstChild){var a=y.getElementsByTagName("track");for(var Z=0;Z<a.length;Z++){var w=a[Z],f=w.getAttribute("lang_code");let p=w.getAttribute("lang_translated"),q=w.getAttribute("name"),D=w.getAttribute("kind"),S=w.getAttribute("id"),F=w.getAttribute("lang_default")==="true",k=w.getAttribute("cantran")===
"true";w=w.getAttribute("vss_id");hi(this.G,new g.iT({languageCode:f,languageName:p,name:q,kind:D,id:S,is_servable:!0,is_translateable:k,vss_id:w,is_default:F}))}y=y.getElementsByTagName("target");a=y.length;for(Z=0;Z<a;Z++)f={languageCode:y[Z].getAttribute("lang_code"),languageName:y[Z].getAttribute("lang_translated"),languageOriginal:y[Z].getAttribute("lang_original"),id:y[Z].getAttribute("id"),isDefault:y[Z].getAttribute("lang_default")==="true"},this.GH[f.languageCode]=f.languageName,this.U.push(f)}this.sA(W,
this.videoId)},
withCredentials:!0})}O(W,l){var n=this.L;l={v:this.videoId,type:"track",lang:W.languageCode,name:W.getName(),kind:W.kind,fmt:l};var y=this.LR.D();y.A("captions_url_add_ei")&&(l.ei=this.eventId);W.translationLanguage&&(l.tlang=g.vN(W));Object.assign(l,y.G);return n=g.eA(n,l)}S(){this.Z&&this.Z.abort()}},L2=/^#(?:[0-9a-f]{3}){1,2}$/i;var ruq=["left","right","center","justify"];var PM=class extends g.ig{constructor(W,l,n,y,a,Z=!1,w=null){super(W,W+l,{priority:n,namespace:"captions"});this.windowId=y;this.text=a;this.append=Z;this.G=w}toString(){return super.toString()}};var aP=class extends g.D7{constructor(W,l,n,y,a,Z,w,f,p,q){var D=q.isInline()&&!0,S={};Object.assign(S,l);Object.assign(S,W.params);Object.assign(S,n);var F={};Object.assign(F,l.Ll);W.params.Ll&&Object.assign(F,W.params.Ll);Object.assign(F,n.Ll);D&&(S.windowOpacity=.6,F.backgroundOpacity=0);S.Ll=F;var k=S.Ib===1,h=[{Y:"span",nR:"captions-text",F9:{style:"word-wrap: normal; display: block;"}}],P=f.X9("caption_edit_on_hover")&&q.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
P&&h.unshift({Y:"button",nR:"caption-edit",F9:{tabindex:"0","aria-label":qSG()},l$:[{Y:"svg",F9:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},l$:[{Y:"path",F9:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({Y:"div",nR:"caption-window",F9:{id:`caption-window-${W.id}`,dir:k?"rtl":"ltr",tabindex:"0",lang:S.lang},l$:h});
this.experiments=f;this.U=[];this.RX=!1;this.S=W;this.Pt=this.e$=null;this.SV=Z;this.P8=w;this.W=null;this.maxWidth=Z*.96;this.maxHeight=w*.96;this.G=S;this.X7=n;this.u$=l;this.K=this.Au("captions-text");W=this.K.style;this.Ht=f.X9("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in W||"WebkitBoxDecorationBreak"in W);this.Ma=bfo(y,a,Z,w);this.Pe=p;P&&(this.L=this.Au("caption-edit"),this.yK(this.L,"click",()=>{this.Pe()}));
this.type=0;this.CR=this.Ma*MRw(F);this.DM=D;this.qa=f.X9("enable_centered_caption_for_tvfilm_video")&&q.getVideoData().isTvfilmVideo;this.GH=q.D().Na().G.KR(g.cMK);y=new g.MJ(this.element,!0);g.Y(this,y);y.subscribe("dragstart",this.hz,this);y.subscribe("dragmove",this.gP,this);y.subscribe("dragend",this.WR,this);this.E4=this.cO=this.YV=this.tA=0;y="";this.G.windowOpacity&&(y=MW(this.G.windowColor),y="rgba("+y[0]+","+y[1]+","+y[2]+","+this.G.windowOpacity+")");a={"background-color":y,display:this.G.isVisible===
!1?"none":"","text-align":ruq[this.G.textAlign]};this.Ht&&(a["border-radius"]=y?`${this.CR*.25}px`:"");(this.O=this.S.params.Ib===2||this.S.params.Ib===3)&&z_w(this,this.element);g.$Y(this.element,a);D&&this.element.parentElement?.style.setProperty("--caption-window-color",y);switch(this.G.mu){case 0:case 1:case 2:g.br(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.br(this.element,"ytp-caption-window-bottom")}}hz(W,l){this.cO=W;this.E4=l;var n=g.ZB(this.element,this.element.parentElement);
this.tA=W-n.x;this.YV=l-n.y}gP(W,l){if(W!==this.cO||l!==this.E4){g.kj(this.element,"ytp-dragging")||g.br(this.element,"ytp-dragging");var n=g.qV(this.element);W=W-this.tA-.02*this.SV;var y=l-this.YV-.02*this.P8,a=(W+n.width/2)/this.maxWidth*3;a=Math.floor(g.Lv(a,0,2));var Z=(y+n.height/2)/this.maxHeight*3;Z=Math.floor(g.Lv(Z,0,2));l=a+Z*3;W=(W+a/2*n.width)/this.maxWidth;W=g.Lv(W,0,1)*100;n=(y+Z/2*n.height)/this.maxHeight;n=g.Lv(n,0,1)*100;this.S.params.mu=l;this.S.params.vE=n;this.S.params.jU=W;this.S.params.isDefault=
!1;this.G.mu=l;this.G.vE=n;this.G.jU=W;this.G.isDefault=!1;this.u$.mu=l;this.u$.vE=n;this.u$.jU=W;this.u$.isDefault=!1;this.k7()}}WR(){g.zH(this.element,"ytp-dragging")}k7(){this.V(this.U)}V(W){var l=this.DM?0:Math.min(this.Se(),this.maxWidth),n=this.nb(),y=this.DM;if(y){var a=getComputedStyle(this.K.parentNode);a=vM(a.borderLeftWidth)+vM(a.borderRightWidth)+vM(a.paddingLeft)+vM(a.paddingRight)}else a=0;var Z=a;a="";this.S.params.Ib===3&&(a="rotate(180deg)");var w=y?`calc(96% - ${Z}px)`:"96%";g.$Y(this.element,
{top:0,left:0,right:"",bottom:"",width:l?`${l}px`:"",height:n?`${n}px`:"","max-width":w,"max-height":w,margin:"",transform:""});this.Db(W);a={transform:a,top:"",left:"",width:l?`${l}px`:"",height:n?`${n}px`:"","max-width":"","max-height":""};w=this.G.mu;var f=this.G.jU,p=this.G.vE;this.qa&&w!=null&&(f=50,w=Math.floor(w/3)*3+1);f=f*.96+2;switch(w){case 0:case 3:case 6:(y=this.G.Ll.fontSizeIncrement)&&y>0&&this.G.Ib!==2&&this.G.Ib!==3&&(f=Math.max(f/(1+y*2),2));a.left=`${f}%`;break;case 1:case 4:case 7:a.left=
`${f}%`;f=0;this.GH||(f=this.K.offsetWidth);l||f?(l=l||f+1,a.width=`${l}px`,a["margin-left"]=y?`${l/-2-Z/2}px`:`${l/-2}px`):(this.GH&&(a.width="max-content"),a.transform+=" translateX(-50%)");break;case 2:case 5:case 8:a.right=`${100-f}%`}y=p*.96+2;switch(w){case 0:case 1:case 2:a.top=`${y}%`;break;case 3:case 4:case 5:a.top=`${y}%`;y=0;this.GH||(y=this.element.clientHeight);(n=n||y)?(a.height=`${n}px`,a["margin-top"]=`${n/-2}px`):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=
`${100-y}%`}g.$Y(this.element,a);this.L&&(this.GH?n=this.CR:(W=QfK(this,W),n=this.qa?W>0?this.K.offsetHeight/W:0:this.K.offsetHeight/W),this.L.style.height=`${n}px`,this.L.style.width=`${n}px`,this.element.style.paddingLeft=`${n+5}px`,this.element.style.paddingRight=`${n+5}px`,this.GH||(W=Number(this.element.style.marginLeft.replace("px",""))-n-5,n=Number(this.element.style.marginRight.replace("px",""))-n-5,this.element.style.marginLeft=`${W}px`,this.element.style.marginRight=`${n}px`))}Db(W){if(this.type===
0&&this.S.params.rW!==void 0&&this.experiments.X9("web_enable_popon_asr_captions")){var l=W,n=this.S.params.rW;if(l.length===0||n<=0)W=[];else{W=[];for(let a=l.length-1;a>=0;a--){var y=l[a];W.unshift(y);let Z=QfK(this,W);if(Z>n){W.shift();typeof y.text==="string"&&(l=y.text.split("\n"),n=Z-n,l.length-n>0&&(n=l.slice(n),y=new PM(y.start,y.end-y.start,y.priority||0,y.windowId,n.join("\n"),y.append,y.G),W.unshift(y)));break}}}}for(y=0;y<W.length&&W[y]===this.U[y];y++);if(this.RX||this.U.length>y)y=0,
this.RX=!1,this.U=[],this.W=this.Pt=this.e$=null,g.KQ(this.K);for(;y<W.length;y++)gnb(this,W[y])}Se(){return 0}nb(){return 0}toString(){return super.toString()}};var Nuw=class{constructor(){this.S=this.time=this.mode=this.Z=0;this.J=new TuK(this);this.K=new TuK(this);this.G=[];this.clear()}clear(){this.S=this.time=this.mode=0;this.G=[];this.reset()}reset(){this.mode=0;this.J.reset(0);this.K.reset(1)}},I3z=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],CLq=class{constructor(){this.type=0}set(W){this.type=W}get(){return this.type}},dxq=class{constructor(){this.state=this.dj=this.La=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}Em(){return this.state!==0}matches(W,l){return this.Em()&&W===this.La&&l===this.dj}},AuT=class{constructor(){this.timestamp=this.G=0}reset(){this.timestamp=
this.G=0}},ZF=class{constructor(W){this.K=W;this.S=[];this.G=this.Z=this.row=0;this.style=new CLq;this.J=0;for(W=0;W<=15;W++){this.S[W]=[];for(let l=0;l<=32;l++)this.S[W][l]=new AuT}}updateTime(W){for(let l=1;l<=15;++l)for(let n=1;n<=32;++n)this.S[l][n].timestamp=W}debugString(){var W="\n";for(let l=1;l<=15;++l){for(let n=1;n<=32;++n){let y=this.S[l][n];W=y.G===0?W+"_":W+String.fromCharCode(y.G)}W+="\n"}return W}reset(W){for(let l=0;l<=15;l++)for(let n=0;n<=32;n++)this.S[l][n].reset();this.J=W;this.G=
0;this.Z=this.row=1}},Hfo=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],R_a=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],XfT=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],x4K=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],Juo=class{constructor(W){this.S=W;this.K=0;this.style=new CLq;this.O=new ZF(this.S);this.W=new ZF(this.S);this.text=new ZF(this.S);this.Z=this.O;this.J=this.W;this.G=this.Z}reset(W,l){this.K=l;this.style.set(2);this.Z=this.O;this.J=this.W;this.G=this.Z;var n=(W<<2)+(l<<1);this.O.reset(n);this.W.reset(n);this.text.reset((W<<
2)+(l<<1)+1)}},TuK=class{constructor(W){this.G=W;this.K=0;this.S=new Juo(this.G);this.O=new Juo(this.G);this.Z=new dxq;this.J=this.S}reset(W){this.K=W;this.Z.clear();this.J=this.S;this.S.reset(W,0);this.O.reset(W,1)}};var Ojb=class{J(){}};var wo=class extends g.$b{reset(){}};var Rv=class extends g.ig{constructor(W,l,n,y,a){super(W,W+l,{priority:n,namespace:"captions"});this.id=y;this.params=a;this.G=[]}toString(){return super.toString()}},HM=0;var $xv=class extends wo{constructor(W){super();this.J=W;this.pens={};this.L={};this.U={};this.K="_"+HM++;this.W={};this.Z=this.G=null;this.O=!0}reset(){this.W={};this.Z=this.G=null;this.O=!0}S(W,l){W=W.firstChild;W.getAttribute("format");l=l||0;Number.isFinite(l);W=Array.from(W.childNodes);for(var n of W)if(n.nodeType===1)switch(n.tagName){case "head":var y=n;break;case "body":var a=n}if(y){y=Array.from(y.childNodes);for(var Z of y)if(Z.nodeType===1)switch(Z.tagName){case "pen":n=Z.getAttribute("id");
y=this.pens;W={};var w=Z.getAttribute("p");w&&Object.assign(W,this.pens[w]);w=xZ(Z,"b");w!=null&&(W.bold=w);w=xZ(Z,"i");w!=null&&(W.italic=w);w=xZ(Z,"u");w!=null&&(W.underline=w);w=YZ(Z,"et");w!=null&&(W.charEdgeStyle=w);w=YZ(Z,"of");w!=null&&(W.offset=w);w=ti(Z,"bc");w!=null&&(W.background=w);w=ti(Z,"ec");w!=null&&(W.lU=w);w=ti(Z,"fc");w!=null&&(W.color=w);w=YZ(Z,"fs");w!=null&&w!==0&&(W.fontFamily=w);w=X2(Z,"sz");w!==void 0&&(W.fontSizeIncrement=w/100-1);w=X2(Z,"bo");w!==void 0&&(W.backgroundOpacity=
w/255);w=X2(Z,"fo");w!==void 0&&(W.textOpacity=w/255);w=YZ(Z,"rb");w!=null&&w!==10&&w!==0&&(W.wP=w>10?w-1:w);w=YZ(Z,"hg");w!=null&&(W.I2=w);y[n]=W;break;case "ws":y=Z.getAttribute("id");this.U[y]=TIv(this,Z);break;case "wp":y=Z.getAttribute("id"),this.L[y]=NIK(this,Z)}}if(a){Z=[];a=Array.from(a.childNodes);for(P of a)if(P.nodeType===1)switch(P.tagName){case "w":this.G=C9o(this,P,l,!1);(a=this.W[this.G.id])&&a.end>this.G.start&&(a.end=this.G.start);this.W[this.G.id]=this.G;Z.push(this.G);break;case "p":var f=
P;W=l;a=[];y=f.getAttribute("w")||this.K;n=!!xZ(f,"a");W=(X2(f,"t")||0)+W;w=X2(f,"d")||5E3;n||(!this.O&&this.Z&&this.Z.windowId===y&&this.Z.end>W&&(this.Z.end=W),this.Z&&this.Z.text==="\n"&&(this.Z.text=""));let V=n?6:5;var p=f.getAttribute("p");p=p?this.pens[p]:null;let m=Array.from(f.childNodes);m.length&&(this.O=f.getAttribute("d")!=null);for(f=0;f<m.length;f++){var q=m[f],D=void 0;f>0&&(n=!0);let B;q.nodeType===1&&(B=q);if(B&&B.tagName==="s"){if((q=(q=B.getAttribute("p"))?this.pens[q]:null)&&
q.wP&&(q.wP===1?(q=m.slice(f,f+4),q.length===4&&(D=BIK(W,w,y,n,V,q,this.pens),f+=3)):D=BIK(W,w,y,n,V,[B],this.pens)),!D){var S=B;D=W;q=w;var F=y,k=n;let N=S.textContent?S.textContent:"";var h=S.getAttribute("p");h=h?this.pens[h]:null;S=X2(S,"t")||0;D=new PM(D+S,q-S,V,F,N,k,h)}}else D=new PM(W,w,V,y,q.textContent||"",n,p);a.push(D);this.Z=D}if(a.length>0){a[0].windowId===this.K&&(this.G=C9o(this,P,l,!0),Z.push(this.G));for(let B of a)B.windowId=this.G.id,this.G.G.push(B),Z.push(B)}}var P=Z}else P=
[];return P}};var uXG=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),UxK=class extends wo{constructor(W){super();this.O=W;this.G=new Map;this.J=new Map;this.K=new Map;this.Z=new Map}reset(){this.Z.clear()}S(W,l){W=JSON.parse(W);if(!W)return[];if(W.pens){var n=W.pens,y=0;for(var a of n){n={};var Z=a.pParentId;Z&&Object.assign(n,this.G.get(Z));a.bAttr&&(n.bold=!0);a.iAttr&&(n.italic=!0);a.uAttr&&(n.underline=!0);Z=a.ofOffset;Z!=null&&(n.offset=Z);a.szPenSize!==void 0&&(n.fontSizeIncrement=a.szPenSize/100-1);
Z=a.etEdgeType;Z!=null&&(n.charEdgeStyle=Z);a.ecEdgeColor!==void 0&&(n.lU=mR(a.ecEdgeColor));Z=a.fsFontStyle;Z!=null&&Z!==0&&(n.fontFamily=Z);a.fcForeColor!==void 0&&(n.color=mR(a.fcForeColor));a.foForeAlpha!==void 0&&(n.textOpacity=a.foForeAlpha/255);a.bcBackColor!==void 0&&(n.background=mR(a.bcBackColor));a.boBackAlpha!==void 0&&(n.backgroundOpacity=a.boBackAlpha/255);(Z=a.rbRuby)&&Z!==10&&(n.wP=Z>10?Z-1:Z,n.textEmphasis=uXG.get(n.wP));a.hgHorizGroup&&(n.I2=a.hgHorizGroup);this.G.set(y++,n)}}if(W.wsWinStyles){y=
W.wsWinStyles;a=0;for(var w of y)y={},(n=w.wsParentId)?Object.assign(y,this.K.get(n)):Object.assign(y,this.O),w.mhModeHint!==void 0&&(y.Ea=w.mhModeHint),w.juJustifCode!==void 0&&(y.textAlign=w.juJustifCode),w.pdPrintDir!==void 0&&(y.Ib=w.pdPrintDir),w.sdScrollDir!==void 0&&(y.CZ=w.sdScrollDir),w.wfcWinFillColor!==void 0&&(y.windowColor=mR(w.wfcWinFillColor)),w.wfoWinFillAlpha!==void 0&&(y.windowOpacity=w.wfoWinFillAlpha/255),this.K.set(a++,y)}if(W.wpWinPositions){a=W.wpWinPositions;w=0;for(var f of a)a=
{},(y=f.wpParentId)&&Object.assign(a,this.J.get(y)),f.ahHorPos!==void 0&&(a.jU=f.ahHorPos),f.apPoint!==void 0&&(a.mu=f.apPoint),f.avVerPos!==void 0&&(a.vE=f.avVerPos),f.ccCols!==void 0&&(a.Ih=f.ccCols),f.rcRows!==void 0&&(a.rW=f.rcRows),this.J.set(w++,a)}if(W.events){W=W.events;f=[];for(let d of W)if(w=(d.tStartMs||0)+l,a=d.dDurationMs||0,d.id)y=String(d.id),W=d4v(this,d,w,a,y),f.push(W),this.Z.set(y,W);else{d.wWinId?y=d.wWinId.toString():(y="_"+HM++,W=d4v(this,d,w,a,y),f.push(W),this.Z.set(y,W));
W=f;var p=d;a===0&&(a=5E3);n=this.Z.get(y);let io=(Z=!!p.aAppend)?6:5,sG=p.segs,EG=null;p.pPenId&&(EG=this.G.get(p.pPenId));for(p=0;p<sG.length;p++){var q=sG[p],D=q.utf8;if(D){var S=q.tOffsetMs||0;let gz=null;q.pPenId&&(gz=this.G.get(q.pPenId));if((n.params.Ea!=null?n.params.Ea:n.G.length>1?1:0)===2&&Z&&D==="\n")continue;q=null;var F=[],k;if(k=gz&&gz.wP===1)a:{k=sG;var h=p;if(h+3>=k.length||!k[h+1].pPenId||!k[h+2].pPenId||!k[h+3].pPenId){k=!1;break a}var P=k[h+1].pPenId;(P=this.G.get(P))&&P.wP&&P.wP===
2?(P=k[h+2].pPenId,P=this.G.get(P),!P||!P.wP||P.wP<3?k=!1:(P=k[h+3].pPenId,k=(P=this.G.get(P))&&P.wP&&P.wP===2?!0:!1)):k=!1}if(k)S=sG[p+1].utf8,q=sG[p+3].utf8,k=sG[p+2].utf8,h=this.G.get(sG[p+2].pPenId),D=VRK(D,S,k,q,h),q=new PM(w,a,io,y,D,Z,gz),p+=3;else{if(D.indexOf("<")>-1){F=gz;k=EG;h=w;P=a;var V=S,m=io,B=Z;let Nq=[];var N=Qg(`<html>${D}</html>`);if(!N.getElementsByTagName("parsererror").length&&N.firstChild?.childNodes.length)for(let rz of N.firstChild.childNodes){N=rz.textContent?.replace(/\n/g,
"")??"";if(rz.nodeType===3&&(!N||N.match(/^ *$/)!=null))continue;let Wq={};Object.assign(Wq,F||k);switch(rz?.tagName){case "b":Wq.bold=!0;break;case "i":Wq.italic=!0;break;case "u":Wq.underline=!0}Nq.push(new PM(h+V,P-V,m,n.id,N,B,Wq))}F=Nq}F.length||(F=[new PM(w+S,a-S,io,n.id,D,Z,gz||EG)])}if(F.length)for(let Nq of F)W.push(Nq),n.G.push(Nq);else q&&(W.push(q),n.G.push(q))}Z=!0}}l=f}else l=[];return l}};var WQK=class extends ih{constructor(W,l,n){super(W);this.videoData=l;this.audioTrack=n;this.U=l.l2}W(W,l,n){wfT(this.videoData.videoId,W.vssId,n.p$)}J(W){if(this.audioTrack)for(let l of this.audioTrack.captionTracks)hi(this.G,l);W.sA()}};var PLz=class extends aP{constructor(W,l,n,y,a,Z,w,f,p,q){super(W,l,n,y,a,Z,w,f,p,q);this.type=1}Db(W){var l=this.S.G;super.Db(W);for(W=W.length;W<l.length;W++){let a=l[W],Z;if(y&&a.G===n)Z=y;else{Z={};Object.assign(Z,a.G);Object.assign(Z,lMJ);var n=a.G;var y=Z}gnb(this,a,Z)}}},lMJ={v7:!0};var A7o=class extends Ojb{constructor(W,l){super();this.trackData=W;this.O=l;this.version=this.K=this.S=this.byteOffset=0;this.Z=[];this.G=new DataView(this.trackData)}J(W,l,n,y,a){if(n<y){let Z="_"+HM++;n=n/1E3-this.O;y=y/1E3-this.O;W=new Rv(n,y-n,5,Z,{textAlign:0,mu:0,jU:l*2.5,vE:W*5.33});a=new PM(n,y-n,5,Z,a);this.Z.push(W);this.Z.push(a)}}},nDK=class extends wo{constructor(W,l){super();this.Z=W;this.J=l;this.track=this.J.languageName==="CC3"?4:0;this.G=new Nuw;this.G.Z=1<<this.track}S(W){W=new A7o(W,
this.Z);if(J7q(W)){for(;W.byteOffset<W.G.byteLength;)for(W.version===0?W.S=BM(W)*(1E3/45):W.version===1&&(W.S=BM(W)*4294967296+BM(W)),W.K=Vg(W);W.K>0;W.K--){var l=Vg(W);let n=Vg(W),y=Vg(W);l&4&&(l&3)===this.track&&(this.track===0||this.track===1)&&(l=this.G,l.G.push({time:W.S,type:this.track,Wr:n,gu:y,order:l.G.length}))}P9J(this.G,W);return W.Z}return[]}reset(){this.G.clear()}};var Hjb=class extends aP{constructor(W,l,n,y,a,Z,w,f,p,q){super(W,l,n,y,a,Z,w,f,p,q);this.type=2;this.gS=[];this.rS=this.vt=this.Y5=0;this.b$=NaN;this.W$=0;this.gH=null;this.ee=new g.Dx(this.xV,433,this);this.L&&(q.createClientVe(this.L,this,167342),this.yK(this.L,"click",()=>{q.logClick(this.L)}),W=new g.MJ(this.element,!0),g.Y(this,W),W.subscribe("hoverstart",()=>{q.logVisibility(this.L,!0)},this));
g.br(this.element,"ytp-caption-window-rollup");g.Y(this,this.ee);g.$Y(this.element,"overflow","hidden")}k7(){var W=this.ee;W.stop();W.Ne()}xV(){this.element.removeEventListener("transitionend",this.xV,!1);g.zH(this.element,"ytp-rollup-mode");this.V(this.gH,!0)}nb(){return this.O?this.rS:this.vt}Se(){return this.O?this.vt:this.rS}V(W,l){this.gH=W;if(this.S.params.rW){var n=0;for(let y=0;y<this.U.length&&n<W.length;y++)this.U[y]===W[n]&&n++;n>0&&n<W.length&&(W=this.U.concat(W.slice(n)));this.W$=this.rS;
this.vt=this.rS=0;super.V(W);U4o(this,l)}super.V(W)}};var yPK=class{constructor(W,l,n,y){this.B=W;this.K=l;this.logger=n;this.nE=y;this.FG=[];this.G=null;this.S=[];this.mL=[];this.Z=null;W=g.cO(this.B.D().experiments,"html5_override_micro_discontinuities_threshold_ms");this.J=W>0?W:10}unload(){this.Z!=null&&(this.B.removeEventListener("sabrCaptionsDataLoaded",this.Z),this.Z=null);this.FG=[];this.G=null;this.S=[];this.B.Zb("sabrCaptionsBufferedRangesUpdated",this.FG)}W(W){return{formatId:g.k8(W.info.pR.info,this.nE),sL:W.info.sL+(this.nE?0:1),startTimeMs:W.info.J*
1E3,durationMs:W.info.W*1E3}}};var aMJ=class extends ih{constructor(W,l){super(l);this.Z=W;this.B=l;this.logger=new g.WC("caps");this.L=this.GH=null;this.V=new yPK(this.B,this,this.logger,this.Z.nE)}W(W,l,n){this.S();l=W.getId();l=l!=null&&l in this.Z.G?this.Z.G[l]:null;l||(l=W.languageCode,l=this.Z.isManifestless?Zjv(this,l,"386"):Zjv(this,l));l&&(this.L=W,this.GH=l,anq(this.V,n),this.B.Zb("sabrCaptionsTrackChanged",g.k8(l.info,this.Z.nE)))}J(W){var l=this.Z.isManifestless?wDq(this,"386"):wDq(this);for(let n of l)hi(this.G,n);
W.sA()}S(){this.L&&(this.L=this.GH=null,this.V.unload(),this.B.Zb("sabrCaptionsTrackChanged",null))}O(){return""}};var fnK="WEBVTT".split("").map(W=>W.charCodeAt(0)),Fsv=class extends wo{constructor(){super()}S(W,l){W instanceof ArrayBuffer&&(W=g.Uv(new Uint8Array(W)));
var n=[];W=W.split(i8J);for(let h=1;h<W.length;h++){var y=W[h],a=l;if(y!==""&&!Z8K.test(y)){var Z=fP.exec(y);if(Z&&Z.length>=4){var w=rL(Z[1]),f=rL(Z[2])-w;w+=a;var p=(Z=Z[3])?Z.split(" "):[];Z={};var q=null;var D="";var S=null,F="";for(let P of p){p=P.split(":");if(p.length!==2)continue;var k=p[1];switch(p[0]){case "line":p=k.split(",");p[0].endsWith("%")&&(q=p[0],Z.vE=Number.parseInt(q,10),p.length===2&&(D=p[1].trim()));break;case "position":p=k.split(",");S=p[0];Z.jU=Number.parseInt(S,10);p.length===
2&&(F=p[1].trim());break;case "align":switch(k){case "start":Z.textAlign=0;break;case "middle":Z.textAlign=2;break;case "end":Z.textAlign=1}}}q||D||(D="end");if(!S)switch(Z.textAlign){case 0:Z.jU=0;break;case 1:Z.jU=100;break;case 2:Z.jU=50}if(Z.textAlign!=null){q=0;switch(D){case "center":q+=3;break;case "end":q+=6;break;default:q+=0}switch(F){case "line-left":q+=0;break;case "center":q+=1;break;case "line-right":q+=2;break;default:switch(Z.textAlign){case 0:q+=0;break;case 2:q+=1;break;case 1:q+=
2}}D=q<0||q>8?7:q;Z.mu=D}y=y.substring(fP.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");F=Z;Z={};if(y.indexOf("<")<0&&y.indexOf("&")<0)a=qnb(w,f,5,F),w=new PM(w,f,5,a.id,y,!1,g.yH(Z)?void 0:Z),n.push(a),n.push(w),a.G.push(w);else for(D=y.split(w3q),D.length===1?(y=5,F=qnb(w,f,y,F)):(q=y=6,F=Object.assign({Ih:32},F),F=new Rv(w,f,q,"_"+HM++,F)),n.push(F),q=w,S=0;S<D.length;S++)if(p=D[S],S%2===0){k=Qg(`<html>${p}</html>`);let P;k.getElementsByTagName("parsererror").length?(P=k.createElement("span"),
P.appendChild(k.createTextNode(p))):P=k.firstChild;sqJ(this,q,f-(q-w),y,F,S>0,P,Z,n)}else q=rL(p)+a}fP.lastIndex=0}}return n}},Z8K=/^NOTE/,i8J=/(?:\r\n|\r|\n){2,}/,fP=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),w3q=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var fMK=class extends g.$b{constructor(W,l){super();this.B=W;this.X=l;this.G=null;this.O4=this.B.HE();this.logger=new g.WC("caps")}clear(){this.G&&this.G.dispose();this.G=null}reset(){this.G&&this.G.reset()}S$(){super.S$();this.clear()}};var bjz={windowColor:"#080808",windowOpacity:0,textAlign:2,mu:7,jU:50,vE:100,isDefault:!0,Ll:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},kWK={windowColor:"#080808",windowOpacity:0,textAlign:0,mu:7,jU:50,vE:100,isDefault:!0,Ll:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.Na("captions",class extends g.ht{constructor(W){super(W);this.B=W;this.gS=[];this.rS={};this.Pt={};this.L=!1;this.S="NONE";this.Z=this.U=this.V=this.dS=this.Ma=null;this.hA={sA:()=>{this.sA()},
p$:(y,a,Z,w,f=0)=>{var p=Number(this.videoData.D().Na().G.KR(g.jbT)??0);f>0&&p>0&&this.videoData.lengthSeconds>0&&f/this.videoData.lengthSeconds>p?this.B.j("tts",{dropcap:f}):this.p$(y,a,Z,w)}};
this.G=null;this.cO="";this.Ht=null;this.X=this.B.D();this.videoData=this.B.getVideoData();this.xV=this.B.AA();this.K={Ll:{}};this.O={Ll:{}};g.Ja(this.videoData)?this.S="OFFLINE":g.CBT(this.videoData,this.B)?this.S="HLS":ijw(this.videoData,this.B)?this.S="SABR_LIVE":g.dKG(this.videoData,this.B)?this.S="LIVE":this.videoData.captionTracks.length?this.S="INNERTUBE":this.videoData.ee&&(this.S="TTS");this.RX=this.X.controlsType==="3";this.Y5=new fMK(this.B,this.X);this.u$=new g.r9(this);this.W=new g.D7({Y:"div",
nR:"ytp-caption-window-container",F9:{id:"ytp-caption-window-container"}});this.vt={top:0,right:0,bottom:0,left:0,width:1,height:1};var l=null,n=g.NO("yt-html5-player-modules::subtitlesModuleData");n&&(l=new g.HF(n));this.storage=l;l=W.ZE();this.E4=!!l?.RX();this.qa=!!l?.e$();this.J=Tb(this);this.GH=EQa(this);g.Y(this,this.Y5);this.J?this.e$=this.b$=null:(this.b$=new g.pa(this.YV,void 0,this),g.Y(this,this.b$),this.e$=new g.Dx(this.k7,2E3,this),g.Y(this,this.e$));g.Y(this,this.u$);g.x0(this.player,
this.W.element,4);g.Y(this,this.W);this.J||this.u$.yK(W,"resize",this.Db);l=g.uM(this.X)&&!g.aU()&&!this.B.isFullscreen();n=this.X.Na().G.KR(g.O4w)&&g.zS(this.X)&&g.Yz;(this.tA=(l||n)&&!this.J&&!this.GH)&&this.u$.yK(W,l?"resize":"fullscreentoggled",this.Se);this.u$.yK(W,"onPlaybackAudioChange",this.nb);this.u$.yK(W,g.yM("captions"),y=>{this.onCueRangeEnter(y)});
this.u$.yK(W,g.ar("captions"),y=>{this.onCueRangeExit(y)});
NW(this,zb()||{});g.Fl(this.player,"onCaptionsModuleAvailable");this.S==="HLS"&&this.J&&(W=this.B.ZE().Ed(),this.qa&&this.u$.yK(W.textTracks,"addtrack",this.fb))}S$(){if(this.J||this.GH){let W=this.B.ZE();W&&!W.OL()&&W.L()}else C2(this,!1);super.S$()}Ry(){if(this.RX)return this.J||this.GH;if(this.S==="HLS")return this.J;var W=this.getAudioTrack();if(vQw(this)){if(!W.captionTracks.length)return!1;if(!this.Z)return!0}W=bN(W,g.om(this.X));return W==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:W==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?
OU(this):Ji(this)||OU(this)?!0:Qqa(this)}load(){super.load();this.U=this.getAudioTrack();if(this.Z)this.G&&(this.Y5.clear(),this.J?eFJ(this,!0):this.player.getPresentingPlayerType()!==3&&this.Z.W(this.G,"json3",this.hA),this.S!=="HLS"&&this.J||this.GH||$Z(this)||g.Fl(this.player,"captionschanged",kZ(this.G)));else{if(this.S==="OFFLINE")var W=new WQK(this.player,this.videoData,this.getAudioTrack());else this.S==="SABR_LIVE"?W=new aMJ(this.videoData.G,this.player):this.S==="HLS"?W=new Yna(this.player):
this.S==="LIVE"?W=new VxG(this.videoData.G,this.player):this.S==="INNERTUBE"?W=new Lsv(this.player,this.videoData,this.getAudioTrack()):(W=this.videoData,W=new BuK(this.player,this.videoData.ee,this.videoData.videoId,W.captionsLanguagePreference||W.oX.captionsLanguagePreference||g.HV(W,"yt:cc_default_lang")||W.oX.qa,this.videoData.jg,this.videoData.eventId));this.Z=W;g.Y(this,this.Z);this.Z.J(this.hA)}}unload(){this.J&&this.G?eFJ(this,!1):(this.e$&&this.e$.e8(),this.player.Qp("captions"),this.gS=
[],this.Z&&this.Z.S(),this.Y5.clear(),this.V&&this.player.us(this.V),this.Db());super.unload();this.player.WH();g.Fl(this.player,"captionschanged",{})}create(){this.Ry()&&this.load();var W;a:{if(this.X.A("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(W=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let l of W)if(l.kind==="asr"&&l.languageCode==="en"){W=
!0;break a}W=!1}W&&this.B.Zb("showpromotooltip",this.W.element)}sA(){var W=bN(this.player.getAudioTrack(),g.om(this.X));var l=W==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?UU(this,this.L):W==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&OU(this)?uN(this):Ji(this)||this.L||Qqa(this)?UU(this,this.L):OU(this)?uN(this):null;if(this.S!=="HLS"&&this.J||this.GH){let n=this.Z.G.G(!0);W=[];for(let y=0;y<n.length;y++){let a=n[y],Z=g.jy("TRACK");Z.setAttribute("kind","subtitles");Z.setAttribute("label",g.QD(a));Z.setAttribute("srclang",
g.vN(a));Z.setAttribute("id",a.toString());this.GH||Z.setAttribute("src",this.Z.O(a,"vtt"));a===l&&Z.setAttribute("default","1");W.push(Z)}l=this.B.ZE();l.vt(W);W=l.Ed();this.qa&&this.u$.yK(W.textTracks,"change",this.W$)}else!this.G&&l&&yO(this,l),g.Fl(this.player,"onCaptionsTrackListChanged"),g.oj(this.player,"onApiChange")}getTrackById(W){var l=this.Z.G.G(!0);for(let n=0;n<l.length;n++)if(l[n].toString()===W)return l[n];return null}W$(){var W=this.B.ZE().Ed().textTracks,l=null;for(let n=0;n<W.length;n++)W[n].mode===
"showing"&&(l=this.getTrackById(W[n].id));(this.loaded?this.G:null)!==l&&yO(this,l,!0)}fb(){this.Z?.J(this.hA)}Wc(){!this.G&&this.J||this.unload()}p$(W,l,n,y){if(W){nP(this,this.G??void 0);this.Z.u$()&&(this.gS=[],this.B.Qp("captions"),EU(this.b$),this.Y5.reset());a:{var a=this.Y5;y=y||0;n=SnK(a,W,n||0);W=[];try{for(let m of n){let B=m.trackData,N=m.Qu,d=a.X.A("safari_live_drm_captions_fix");if(typeof B!=="string"){n=W;var Z=n.concat;if(d&&pDK(B))var w=oQT(a,B,N);else{var f=a,p=l,q=B,D=N,S=y;if(!Ofw(q))throw Error("Invalid binary caption track data");
f.G||(f.G=new nDK(S,p));w=f.G.S(q,D)}var F=Z.call(n,w)}else{if(B.substring(0,6)==="WEBVTT")var k=W.concat(oQT(a,B,N));else{n=W;var h=n.concat;b:{p=a;f=l;if(B[0]==="{")try{p.G||(p.G=new UxK(cuo(f)));var P=p.G.S(B,N);break b}catch(EG){g.TC(EG);P=[];break b}let io=Qg(B);if(!io||!io.firstChild){let EG=Error("Invalid caption track data");EG.params=B;throw EG;}if(io.firstChild.tagName==="timedtext"){if(Number(io.firstChild.getAttribute("format"))===3){q=io;p.G||(p.G=new $xv(cuo(f)));P=p.G.S(q,N);break b}let EG=
Error("Unsupported subtitles format in web player (Format2)");EG.params=B;throw EG;}if(io.firstChild.tagName==="transcript"){let EG=Error("Unsupported subtitles format in web player (Format1)");EG.params=B;throw EG;}let sG=Error("Invalid caption track data");sG.params=B;throw sG;}k=h.call(n,P)}F=k}W=F}var V=W;break a}catch(m){g.lA(a.logger,187101178,`Captions parsing failed: ${m.message}. `);a.clear();V=[];break a}V=void 0}this.X.A("html5_sabr_live_support_subfragmented_captions")&&this.Z instanceof
aMJ&&(l=this.Z.V,a=[],V.length>0&&(a=V.slice(l.S.length)),l.S=!l.G||l.G.info.dY?[]:V,V=a);l=this.X.Na().G.KR(g.Lcw);V.length>0&&(!l||this.cO!==this.G?.Z())&&(a=this.G,this.wx(a,!!a,$Z(this)?"g":this.L?"m":"s"),l&&(this.cO=this.G?.Z()||""));this.player.us(V,void 0,this.S==="LIVE"||this.S==="SABR_LIVE");!this.L||this.GH||$Z(this)||g.qP(this.X)||g.w2(this.X)||g.Uf(this.X)||this.X.L==="shortspage"||this.player.isInline()||(this.e$.e8(),V=r7v({mu:0,jU:5,vE:5,rW:2,textAlign:0,Ib:0,lang:"en-GB"}),this.dS=
[V],l=["Click "," for settings"],this.Ma||(a=new g.VTw({Y:"svg",F9:{height:"100%",version:"1.1",viewBox:"0 0 36 36",width:"100%"},l$:[{Y:"path",HF:!0,F9:{d:"m 23.94,18.78 c .03,-0.25 .05,-0.51 .05,-0.78 0,-0.27 -0.02,-0.52 -0.05,-0.78 l 1.68,-1.32 c .15,-0.12 .19,-0.33 .09,-0.51 l -1.6,-2.76 c -0.09,-0.17 -0.31,-0.24 -0.48,-0.17 l -1.99,.8 c -0.41,-0.32 -0.86,-0.58 -1.35,-0.78 l -0.30,-2.12 c -0.02,-0.19 -0.19,-0.33 -0.39,-0.33 l -3.2,0 c -0.2,0 -0.36,.14 -0.39,.33 l -0.30,2.12 c -0.48,.2 -0.93,.47 -1.35,.78 l -1.99,-0.8 c -0.18,-0.07 -0.39,0 -0.48,.17 l -1.6,2.76 c -0.10,.17 -0.05,.39 .09,.51 l 1.68,1.32 c -0.03,.25 -0.05,.52 -0.05,.78 0,.26 .02,.52 .05,.78 l -1.68,1.32 c -0.15,.12 -0.19,.33 -0.09,.51 l 1.6,2.76 c .09,.17 .31,.24 .48,.17 l 1.99,-0.8 c .41,.32 .86,.58 1.35,.78 l .30,2.12 c .02,.19 .19,.33 .39,.33 l 3.2,0 c .2,0 .36,-0.14 .39,-0.33 l .30,-2.12 c .48,-0.2 .93,-0.47 1.35,-0.78 l 1.99,.8 c .18,.07 .39,0 .48,-0.17 l 1.6,-2.76 c .09,-0.17 .05,-0.39 -0.09,-0.51 l -1.68,-1.32 0,0 z m -5.94,2.01 c -1.54,0 -2.8,-1.25 -2.8,-2.8 0,-1.54 1.25,-2.8 2.8,-2.8 1.54,0 2.8,1.25 2.8,2.8 0,1.54 -1.25,2.8 -2.8,2.8 l 0,0 z",
fill:"#fff"}}]}),g.Y(this,a),this.Ma=a.element),a=V.end-V.start,(F=g.QD(this.G))&&this.dS.push(new PM(V.start,a,0,V.id,F)),this.dS.push(new PM(V.start,a,0,V.id,l[0]),new PM(V.start,a,0,V.id,this.Ma,!0),new PM(V.start,a,0,V.id,l[1],!0)),this.player.us(this.dS),g.S7(this.e$));!this.L||this.GH||$Z(this)||(this.X.A("enable_player_captions_persistence_state_machine")?Ai(this,!0):g.om(this.X)?Ww(this,!0):lh(this,!0),this.U&&(this.U.J=this.G),this.player.WH());this.L=!1}}onCueRangeEnter(W){this.gS.push(W);
EU(this.b$)}onCueRangeExit(W){g.ly(this.gS,W);this.Z instanceof VxG&&this.Z.GH&&this.player.yU([W]);EU(this.b$)}getCaptionWindowContainerId(){return this.W.element.id}k7(){MxT(this,this.dS);this.dS=null}YV(){if(!this.tA||!this.J){this.b$.stop();g.ap(this.Pt);this.gS.sort(g.nr);var W=this.gS;if(this.V){let l=g.m0(W,function(n){return this.V.indexOf(n)===-1},this);
l.length&&(W=l)}for(let l of W)l instanceof Rv?jqb(this,l):GWG(this,l);for(let [l,n]of Object.entries(this.rS)){let y=l,a=n;this.Pt[y]?(a.element.parentNode||(a instanceof Hjb||a instanceof PLz||g.dk(this.rS,(Z,w)=>{w!==y&&Z.S.params.mu===a.S.params.mu&&Z.S.params.jU===a.S.params.jU&&Z.S.params.vE===a.S.params.vE&&(Z.dispose(),delete this.rS[w]);return w===y},this),this.W.element.appendChild(a.element)),a.V(this.Pt[y])):(a.dispose(),delete this.rS[y])}}}KU(){NW(this,{},!0);
g.Fl(this.player,"captionssettingschanged")}IB(){var W=this.X.A("enable_player_captions_new_style_defaults")?kWK:bjz,l=W.Ll;W={background:l.background,backgroundOpacity:l.backgroundOpacity,charEdgeStyle:l.charEdgeStyle,color:l.color,fontFamily:l.fontFamily,fontSizeIncrement:l.fontSizeIncrement,fontStyle:l.bold&&l.italic?3:l.bold?1:l.italic?2:0,textOpacity:l.textOpacity,windowColor:W.windowColor,windowOpacity:W.windowOpacity};l=zb()||{};l.background!=null&&(W.background=l.background);l.backgroundOverride!=
null&&(W.backgroundOverride=l.backgroundOverride);l.backgroundOpacity!=null&&(W.backgroundOpacity=l.backgroundOpacity);l.backgroundOpacityOverride!=null&&(W.backgroundOpacityOverride=l.backgroundOpacityOverride);l.charEdgeStyle!=null&&(W.charEdgeStyle=l.charEdgeStyle);l.charEdgeStyleOverride!=null&&(W.charEdgeStyleOverride=l.charEdgeStyleOverride);l.color!=null&&(W.color=l.color);l.colorOverride!=null&&(W.colorOverride=l.colorOverride);l.fontFamily!=null&&(W.fontFamily=l.fontFamily);l.fontFamilyOverride!=
null&&(W.fontFamilyOverride=l.fontFamilyOverride);l.fontSizeIncrement!=null&&(W.fontSizeIncrement=l.fontSizeIncrement);l.fontSizeIncrementOverride!=null&&(W.fontSizeIncrementOverride=l.fontSizeIncrementOverride);l.fontStyle!=null&&(W.fontStyle=l.fontStyle);l.fontStyleOverride!=null&&(W.fontStyleOverride=l.fontStyleOverride);l.textOpacity!=null&&(W.textOpacity=l.textOpacity);l.textOpacityOverride!=null&&(W.textOpacityOverride=l.textOpacityOverride);l.windowColor!=null&&(W.windowColor=l.windowColor);
l.windowColorOverride!=null&&(W.windowColorOverride=l.windowColorOverride);l.windowOpacity!=null&&(W.windowOpacity=l.windowOpacity);l.windowOpacityOverride!=null&&(W.windowOpacityOverride=l.windowOpacityOverride);return W}kH(W,l){var n={};Object.assign(n,zb());Object.assign(n,W);NW(this,n,l);g.Fl(this.player,"captionssettingschanged")}Db(){!this.J&&this.loaded&&(g.$U(this.rS,function(W,l){W.dispose();delete this.rS[l]},this),this.YV())}e7(W,l){switch(W){case "fontSize":if(isNaN(l))break;
W=g.Lv(l,-2,4);this.kH({fontSizeIncrement:W});return W;case "reload":l&&!this.J&&yO(this,this.G,!0);break;case "stickyLoading":l!==void 0&&this.X.W&&(this.X.A("enable_player_captions_persistence_state_machine")?Ai(this,!(!l||!l.userInitiated)):g.om(this.X)?Ww(this,!!l):lh(this,!!l));break;case "track":return RFa(this,l);case "tracklist":return this.Z?g.VA(this.Z.G.G(!(!l||!l.includeAsr)),n=>kZ(n)):[];
case "translationLanguages":return this.Z?this.Z.U.map(n=>Object.assign({},n)):[];
case "sampleSubtitles":this.J||l===void 0||C2(this,!!l);break;case "sampleSubtitlesCustomized":this.J||C2(this,!!l,l);break;case "recommendedTranslationLanguages":return g.lp();case "defaultTranslationSourceTrackIndices":return this.Z?this.Z.vt:[]}}getOptions(){var W="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.W&&W.push("stickyLoading");return W}Oz(){var W=this.G;if(this.B.gL("captions")){if(this.X.A("html5_modify_caption_vss_logging"))return(W=this.videoData.ha??
null)?{cc:g.eN(W)}:{};if(W){let l=W.vssId;W.translationLanguage&&l&&(l=`t${l}.${g.vN(W)}`);return{cc:l}}}return{}}Z_(W){this.isSubtitlesOn()?(this.X.A("enable_player_captions_persistence_state_machine")&&W?Ai(this,!1):g.om(this.X)?Ww(this,!1):lh(this,!1),nP(this),yO(this,null,!0)):this.rz(W)}rz(W){var l=$Z(this)||!this.G?UU(this,!0):this.G;l&&this.GR(l.vssId,"m");this.isSubtitlesOn()||yO(this,l,this.X.A("enable_player_captions_persistence_state_machine")?W:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.G&&!$Z(this)}nb(){var W=$Z(this);OU(this,W)?yO(this,this.getAudioTrack().G,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),vQw(this)&&(this.L=!1,this.G=null,this.Z&&(this.Z.dispose(),this.Z=null)),this.Ry()&&(W?yO(this,UU(this,!1),!1):this.load()))}Pa(W){if(this.X.experiments.X9("web_enable_captions_set_target_container")&&W!==this.Ht){var l=this.W.element;l.parentNode&&g.Hu(l);(this.Ht=W)?(this.Ht.appendChild(l),l.style.position="absolute",l.style.bottom="0",l.style.left=
"0",l.style.width="100%",l.style.height="auto",l.style.top="auto"):(g.x0(this.player,l,4),l.style.position="absolute",l.style.bottom="auto",l.style.left="0",l.style.width="100%",l.style.height="100%",l.style.top="0");this.Db()}}Ji(W){W&&(this.vt={top:W.top,right:W.right,bottom:W.bottom,left:W.left,width:1-W.left-W.right,height:1-W.top-W.bottom},this.W.element.style.top=`${this.vt.top*100}%`,this.W.element.style.left=`${this.vt.left*100}%`,this.W.element.style.width=`${this.vt.width*100}%`,this.W.element.style.height=
`${this.vt.height*100}%`,this.W.element.style.position="absolute",W=KsG(this))&&(this.W.element.style.width=`${W.width}px`,this.W.element.style.height=`${W.height}px`)}onVideoDataChange(W,l){W==="newdata"&&(this.videoData=l,this.loaded&&this.unload(),this.L=!1,this.G=null,this.Z&&(this.Z.dispose(),this.Z=null,g.Fl(this.player,"captionschanged",{})),this.Ry()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}Se(){if(this.X.Na().G.KR(g.O4w)){if(this.loaded&&this.unload(),this.RX=this.B.isFullscreen()||
this.X.controlsType==="3",this.J=Tb(this),this.GH=EQa(this),this.J||this.GH){var W=this.B.ZE();W&&!W.OL()&&W.L();this.sA()}}else(W=this.B.ZE())&&!W.OL()&&W.L(),this.B.isFullscreen()?(this.J=this.RX=!0,this.loaded&&this.sA()):(this.RX=this.X.controlsType==="3",this.J=Tb(this));yO(this,this.G)}CR(){var W=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;W&&g.SZ(this.player,"innertubeCommand",W)}wx(W,l,n){var y=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,a="";W&&
(a=W.vssId,a=a.replace(y,""));var Z="";if(W&&W.getId()&&this.X.Na().G.KR(g.Lcw))if(Z=W.getId()||"",Z.includes(";"))Z=Z.split(";").map(f=>f.replace(y,"")).join(";");
else{Z=Z.replace(y,"");var w="";W.getXtags()&&(w=W.getXtags(),w=w.replace(y,""),Z=Z.concat(`;${w}`))}else W&&W.getId()&&(Z=W.getId()||""),w="",W&&W.getXtags()&&(w=W.getXtags(),w=w.replace(y,""),Z=Z.concat(`;${w}`));this.S==="HLS"&&(Z="");this.B.wx(l?a:"",l?Z:"",n)}GR(W,l){W=(W||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");W.length>0&&this.B.GR(W,l)}});})(_yt_player);
